// Real browser proof using only loopback fixtures and disposable browser state.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { once, EventEmitter } from 'node:events';
import { chromium } from 'playwright-core';
import { startAgentServer } from '../lense/agent-server.mjs';
import { interceptOrigin } from '../lense/intercept.mjs';

test('real browser: agent API inspects DOM/styles/network, resizes, captures and isolates foreign tabs', { timeout: 60_000 }, async (t) => {
  const work = fs.mkdtempSync(path.join(os.tmpdir(), 'pp-agent-browser-'));
  let browser;
  let agent;
  const servers = [];
  // Each step's name and duration; printed when the test does not finish, to name a stuck step.
  const trail = [];
  let finished = false;
  const step = async (name, action) => {
    const entry = { name, startedMs: Date.now() };
    trail.push(entry);
    try { return await action(); } finally { entry.ms = Date.now() - entry.startedMs; }
  };
  t.after(async () => {
    if (!finished) console.log(`agent-server steps: ${JSON.stringify(trail.map(({ name, ms }) => ({ name, ms: ms ?? 'unfinished' })))}`);
    await agent?.close(); await browser?.close();
    for (const server of servers) { server.closeAllConnections(); await new Promise((resolve) => server.close(resolve)); }
    fs.rmSync(work, { recursive: true, force: true, maxRetries: 5 });
  });
  const serve = async (handler) => {
    const server = http.createServer(handler);
    server.on('connect', (_request, socket) => { socket.on('error', () => {}); socket.end('HTTP/1.1 403 Forbidden\r\n\r\n'); });
    server.listen(0, '127.0.0.1'); await once(server, 'listening'); servers.push(server);
    return `http://127.0.0.1:${server.address().port}`;
  };
  const external = await serve((request, response) => request.url.startsWith('/missing') ? response.writeHead(404).end('missing fixture asset') : response.writeHead(200, { 'content-type': 'text/html' }).end('<h1>Foreign sign-in fixture</h1>'));
  const methods = [];
  const documents = [];
  const origin = await serve((request, response) => {
    methods.push(request.method);
    if (request.url.startsWith('/chapter/')) documents.push({ method: request.method, url: request.url });
    if (request.url.startsWith('/data')) return response.writeHead(200, { 'content-type': 'application/json' }).end('{"privateBody":"neverCaptured"}');
    if (request.url === '/redirect') return response.writeHead(302, { location: external }).end();
    response.writeHead(200, { 'content-type': 'text/html' }).end(`<!doctype html><title>Agent fixture</title><style>tr{color:rgb(1, 2, 3)}#paqvilo-panel{position:fixed;inset:0;background:red;pointer-events:none}</style><body><table><tr><th>Name</th><th>Status</th></tr><tr style="width:100%"><td>Example</td><td>Ready</td></tr></table><input type="password" value="inputSecret"><textarea>textareaSecret</textarea><div contenteditable>editableSecret</div><a href="next?token=linkSecret">Next</a><form id="fixture-post" method="post" action="/chapter/?filter=ready#posted"><button id="submit">Submit to fixture</button></form><div id="paqvilo-panel">Developer panel</div><script>console.error('token=consoleSecret');fetch('/data?token=requestSecret');</script><script src="${external}/missing.js?token=cdnSecret"></script></body>`);
  });
  const channel = process.env.PAQVILO_BROWSER || (process.platform === 'win32' ? 'msedge' : 'chromium');
  browser = await chromium.launch({ channel: channel === 'chromium' ? undefined : channel, headless: true, proxy: { server: origin, bypass: '127.0.0.1,localhost' }, args: ['--disable-background-networking', '--disable-component-update', '--disable-sync', '--host-resolver-rules=MAP * ~NOTFOUND, EXCLUDE 127.0.0.1, EXCLUDE localhost'] });
  const context = await browser.newContext({ serviceWorkers: 'block' });
  const page = await context.newPage();
  const session = Object.assign(new EventEmitter(), { cfg: { stateDir: work, origin, sourceDir: work, siteName: 'fixture', envName: 'loopback', site: { scope: 'all' } }, baseline: { available: true, spec: 'HEAD', commit: 'abc' }, model: { webFileByUrl: new Map(), warnings: [] }, rewriter: { activeBlocks: 0, patches: [], unsupported: [] }, changedFiles: new Set(), pageHits: new WeakMap(), rel: (file) => path.relative(work, file) });
  agent = await startAgentServer({ session, context });
  const discovery = JSON.parse(fs.readFileSync(agent.discoveryFile, 'utf8'));
  const call = (url, body) => step(`${body === undefined ? 'GET' : 'POST'} ${url}${body?.url ? ` ${body.url}` : ''}`, () => fetch(agent.endpoint + url, { method: body === undefined ? 'GET' : 'POST', headers: { authorization: `Bearer ${discovery.token}`, ...(body === undefined ? {} : { 'content-type': 'application/json' }) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }));
  await step('page.goto /chapter/', () => page.goto(origin + '/chapter/'));
  const rows = await (await call('/v1/pages/1/dom', { selector: 'table tr', styles: ['display', 'color'] })).json();
  assert.equal(rows.elements.length, 2);
  assert.equal(rows.elements[1].text, 'Example Ready');
  assert.equal(rows.elements[1].style.color, 'rgb(1, 2, 3)');
  assert.equal(rows.elements[1].attributes.style, 'width:100%');
  assert.ok(rows.elements[1].rect.width > 0);
  const all = await (await call('/v1/pages/1/dom', {})).json();
  for (const secret of ['inputSecret', 'textareaSecret', 'editableSecret', 'linkSecret']) assert.equal(JSON.stringify(all).includes(secret), false);
  const history = await (await call('/v1/events')).json();
  assert.ok(history.events.some((event) => event.type === 'response' && event.status === 404 && event.url.startsWith(external)));
  assert.ok(history.events.some((event) => event.type === 'requestfinished' && event.timing.responseEnd >= 0));
  for (const secret of ['privateBody', 'neverCaptured', 'requestSecret', 'cdnSecret', 'consoleSecret']) assert.equal(JSON.stringify(history).includes(secret), false);
  const resized = await call('/v1/pages/1/viewport', { width: 800, height: 600 });
  assert.equal(resized.status, 200); assert.deepEqual(page.viewportSize(), { width: 800, height: 600 });
  const hidden = Buffer.from(await (await call('/v1/pages/1/screenshot', { fullPage: true })).arrayBuffer());
  const shown = Buffer.from(await (await call('/v1/pages/1/screenshot', { includePanel: true })).arrayBuffer());
  assert.deepEqual([...hidden.subarray(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10]);
  assert.equal(hidden.equals(shown), false);
  assert.equal(await page.locator('#paqvilo-panel').evaluate((node) => getComputedStyle(node).visibility), 'visible', 'screenshot style is restored');
  assert.equal(await step('in-page fetch to agent', () => page.evaluate(async (endpoint) => { try { await fetch(endpoint + '/v1/session'); return true; } catch { return false; } }, agent.endpoint)), false, 'browser CORS access is rejected');
  assert.equal((await call('/v1/pages/1/navigate', { url: '/chapter/?filter=ready#table' })).status, 200);
  const getsBeforeReload = documents.filter((document) => document.method === 'GET').length;
  const reloaded = await call('/v1/pages/1/reload', {});
  assert.equal(reloaded.status, 200, JSON.stringify(await reloaded.json()));
  assert.equal(documents.filter((document) => document.method === 'GET').length, getsBeforeReload + 1);
  assert.equal(new URL(page.url()).hash, '#table');
  assert.equal(new URL(page.url()).searchParams.get('filter'), 'ready');
  assert.ok(new URL(page.url()).searchParams.has('paqvilo'));
  assert.equal((await call('/v1/pages/1/navigate', { url: '/chapter/?filter=ready&filter=other#' })).status, 200);
  const beforeEmptyFragment = documents.filter((document) => document.method === 'GET').length;
  assert.equal((await call('/v1/pages/1/reload', {})).status, 200);
  assert.equal(documents.filter((document) => document.method === 'GET').length, beforeEmptyFragment + 1, 'an empty fragment also forces a real GET');
  assert.ok(page.url().endsWith('#'));
  assert.deepEqual(new URL(page.url()).searchParams.getAll('filter'), ['ready', 'other']);
  await step('submit POST form', () => Promise.all([page.waitForURL(origin + '/chapter/?filter=ready#posted'), page.locator('#submit').click()]));
  assert.equal(methods.filter((method) => method === 'POST').length, 1);
  const refused = await call('/v1/pages/1/reload', {});
  assert.equal(refused.status, 409);
  assert.equal((await refused.json()).error.code, 'unsafe_reload');
  assert.equal(methods.filter((method) => method === 'POST').length, 1, 'API reload never repeats a submitted POST');
  const lateGet = page.waitForRequest((request) => request.isNavigationRequest() && request.url().startsWith(origin + '/chapter/'));
  const detach = await step('interceptOrigin', () => interceptOrigin(context, origin, (route) => route.fallback()));
  assert.equal((await step('late GET retry', () => lateGet)).method(), 'GET', 'late interception retry requests GET even for a POST document with a fragment');
  await step('waitForLoadState', () => page.waitForLoadState('load'));
  assert.equal(methods.filter((method) => method === 'POST').length, 1);
  assert.equal(new URL(page.url()).hash, '#posted');
  await step('detach', () => detach());
  assert.equal((await call('/v1/pages/1/navigate', { url: '/chapter/' })).status, 200);
  assert.equal((await call('/v1/pages/1/navigate', { url: external })).status, 403);
  assert.equal((await call('/v1/pages/1/navigate', { url: '/redirect' })).status, 403, 'same-origin navigation can redirect but foreign page inspection remains denied');
  assert.equal((await call('/v1/pages/1/dom', {})).status, 404);
  const state = await (await call('/v1/session')).json();
  assert.equal(state.access.externalTabCount, 1); assert.equal(state.pages.length, 0);
  assert.equal(methods.filter((method) => method !== 'GET').length, 1, 'only the explicit loopback fixture submission used POST');
  await agent.close();
  assert.equal(fs.existsSync(agent.discoveryFile), false);
  finished = true;
});
