// Live Lense mode, using only invented exports and a disposable loopback portal.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import { once } from 'node:events';
import { chromium } from 'playwright-core';
import { OverlaySession } from '../lense/session.mjs';
import { attachSession } from '../lense/browser.mjs';
import { enablePanel } from '../lense/panel.mjs';
import { SITE } from '../test/fixture.mjs';
import { inspectionFixture, addNativeInspectionFixture } from '../test/source-inspection-fixture.mjs';

test('live Inspect works without Mirage and opens exact project Solution sources, locates controls and refreshes navigation', { timeout: 90_000 }, async (t) => {
  const fx = inspectionFixture();
  addNativeInspectionFixture(fx);
  const nativeFormFile = path.join(fx.solution, 'Entities/fx_widget/FormXml/main/widget-form.xml');
  fs.writeFileSync(nativeFormFile, fs.readFileSync(nativeFormFile, 'utf8').replace('id="fx_title"', 'id="fx_title" uniqueid="native-editor"').replace('</tabs>', '</tabs><controlDescriptions><controlDescription forControl="native-editor"><customControl name="fx_Example.Editor" formFactor="0"><parameters><value>fx_title</value></parameters></customControl></controlDescription></controlDescriptions>'));
  fs.writeFileSync(path.join(fx.portal, 'basic-forms/Native-editor.basicformmetadata.yml'), 'adx_entityformmetadataid: native-editor-metadata\nadx_entityform: widget-edit\nadx_type: 100000000\nadx_attributelogicalname: fx_title\nadx_controlstyle: 756150001');
  const nativeControlDir = path.join(fx.solution, 'Controls/fx_Example.Editor'); fs.mkdirSync(nativeControlDir, { recursive: true });
  fs.writeFileSync(path.join(nativeControlDir, 'ControlManifest.xml'), '<manifest><control namespace="Example" constructor="Editor" control-type="standard"><property name="value" of-type="SingleLine.Text" usage="bound"/><resources><code path="bundle.js" order="1"/></resources></control></manifest>');
  fs.writeFileSync(path.join(nativeControlDir, 'ControlManifest.xml.data.xml'), '<CustomControl><Name>fx_Example.Editor</Name></CustomControl>');
  fs.writeFileSync(path.join(nativeControlDir, 'bundle.js'), 'window.Example = {};');
  const assetCode = "window.widgetFeature = true; function api(path) { return fetch('/_api/' + path); } api('fx_widgets(record-private-id)?$filter=private-filter');";
  fs.writeFileSync(path.join(fx.portal, 'web-files/widget.js'), assetCode);
  const requests = [], opened = [], errors = [];
  const server = http.createServer((request, response) => {
    const pathname = new URL(request.url, 'http://fixture.invalid').pathname;
    requests.push(pathname);
    if (pathname === '/widget.js') return response.writeHead(200, { 'content-type': 'text/javascript' }).end(assetCode);
    if (pathname.startsWith('/_api/')) return response.writeHead(200, { 'content-type': 'application/json' }).end('{"value":[]}');
    if (pathname === '/widget.css') return response.writeHead(200, { 'content-type': 'text/css' }).end('.widget { margin: 1rem; }');
    if (pathname === '/favicon.ico') return response.writeHead(204).end();
    response.writeHead(200, { 'content-type': 'text/html' }).end(`<!doctype html><html><head><title>Widget fixture</title><link rel="stylesheet" href="/widget.css?private=excluded"></head><body><h1>Widgets</h1><form data-entityname="fx_widget"><span data-form-layout='{"Id":"widget-edit","EntityName":"fx_widget"}'></span><label for="fx_title">Title</label><input id="fx_title" name="fx_title" value="private-value-must-not-be-inspected"><input type="password" id="password" value="private-password"></form><div class="subgrid" id="ChildGrid"><div class="entity-grid" data-selected-view="child-view"></div></div><a href="/other/" id="other">Other page</a><script src="/widget.js"></script></body></html>`);
  });
  let browser, panel, detach;
  t.after(async () => {
    await panel?.dispose(); await detach?.(); await browser?.close();
    server.closeAllConnections(); await new Promise((resolve) => server.close(resolve));
    fx.cleanup();
  });
  server.listen(0, '127.0.0.1'); await once(server, 'listening');
  const origin = `http://127.0.0.1:${server.address().port}`;
  const channel = process.env.PAQVILO_BROWSER || (process.platform === 'win32' ? 'msedge' : 'chromium');
  browser = await chromium.launch({ channel: channel === 'chromium' ? undefined : channel, headless: true, args: ['--disable-background-networking', '--disable-component-update', '--disable-sync'] });
  const context = await browser.newContext({ serviceWorkers: 'block', viewport: { width: 1440, height: 1000 } });
  context.setDefaultTimeout(12_000);
  await context.route('**/*', (route) => new URL(route.request().url()).origin === origin ? route.fallback() : route.abort());
  const session = new OverlaySession({ sourceDir: fx.portal, origin, site: structuredClone(SITE), sourceMaps: false, siteName: 'Widget fixture', envName: 'loopback', stateDir: fx.work, browser: {}, mirageConfig: { project: fx.project } });
  detach = await attachSession(context, session);
  panel = enablePanel(context, session, { open: async (...args) => { opened.push(args); return null; } });
  const page = await context.newPage(); page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(origin, { waitUntil: 'load' });
  await page.waitForFunction(() => performance.getEntriesByType('resource').some((entry) => entry.name.includes('/_api/')));
  const scope = page.locator('#paqvilo-panel');
  await scope.locator('.pill').click();
  await scope.locator('[data-act="tab"][data-v="runtime"]').click();
  await scope.locator('[data-group="runtime-forms"]').getByText('Widget form', { exact: false }).first().waitFor();
  assert.equal(await scope.getByText('Live portal · local source inspection').count(), 1);
  assert.equal(await scope.getByText('Live access', { exact: true }).count(), 1);
  assert.equal(await scope.locator('[data-act="tab"][data-v="tweaks"]').count(), 0);
  assert.equal(await scope.locator('[data-group="runtime-permissions"]').getByText('Readers view widgets').count(), 1);
  assert.equal(await scope.locator('[data-group="runtime-permissions"]').getByText('Editors update widgets').count(), 1);
  await scope.locator('[data-group="runtime-api"]').getByText('table fx_widget · observed request; IDs and query values excluded').waitFor();
  await scope.locator('[data-group="runtime-native"]').getByText('Child records', { exact: true }).waitFor();
  await scope.locator('[data-group="runtime-forms"]').getByText('Read child', { exact: true }).waitFor();
  await scope.locator('[data-group="runtime-pcf"]').getByText('fx_Example.Editor', { exact: true }).waitFor();
  await scope.locator('[data-group="runtime-pcf"] [data-rel$="ControlManifest.xml"] [data-act="open"]').first().click();
  await new Promise((resolve) => setTimeout(resolve, 100));
  assert.equal(opened.at(-1)[1], path.join(nativeControlDir, 'ControlManifest.xml'));
  await scope.locator('[data-group="runtime-pcf"] [data-rel*="FormXml"] [data-act="open"]').first().click();
  await new Promise((resolve) => setTimeout(resolve, 100));
  assert.equal(opened.at(-1)[1], nativeFormFile);
  if (process.env.PAQVILO_EVIDENCE_DIR) {
    fs.mkdirSync(process.env.PAQVILO_EVIDENCE_DIR, { recursive: true });
    await page.screenshot({ path: path.join(process.env.PAQVILO_EVIDENCE_DIR, 'lense-inspect-live.png') });
  }
  await scope.locator('[data-group="runtime-forms"] [data-rel*="FormXml"] [data-act="open"]').first().click();
  await new Promise((resolve) => setTimeout(resolve, 100));
  assert.equal(opened.at(-1)[1], path.join(fx.solution, 'Entities/fx_widget/FormXml/main/widget-form.xml'));
  await scope.locator('[data-group="runtime-page-sources"] [data-rel$="custom_javascript.js"] [data-act="open"]').first().click();
  await new Promise((resolve) => setTimeout(resolve, 100));
  assert.equal(opened.at(-1)[1], path.join(fx.portal, 'web-pages/home/Home.webpage.custom_javascript.js'));
  await scope.locator('[data-group="runtime-views"] .row').filter({ hasText: 'Related children' }).locator('[data-act="open"]').first().click();
  await new Promise((resolve) => setTimeout(resolve, 100));
  assert.equal(opened.at(-1)[1], path.join(fx.solution, 'Entities/fx_child/SavedQueries/child-view.xml'));
  await scope.locator('[data-act="inspect-section"][data-v="components"]').click();
  assert.equal(await scope.locator('[data-group="runtime-page-sources"]').count(), 0);
  await scope.locator('[data-group="runtime-columns"] [data-act="inspect-locate"][data-field="fx_title"]').click();
  assert.match(await page.locator('#fx_title').evaluate((node) => node.style.outline), /3px/);
  await scope.locator('[data-act="inspect-pick"]').click();
  await page.locator('#fx_title').click();
  await scope.getByText('Selected: input#fx_title', { exact: true }).waitFor();
  await scope.locator('[data-act="inspect-section"][data-v="all"]').click();
  const snapshot = JSON.stringify(await page.evaluate(async (token) => (await fetch('/__paqvilo/api/inspect', { method: 'POST', headers: { 'content-type': 'application/json', 'x-paqvilo-token': token }, body: '{}' })).json(), panel.stateFor(page).token));
  assert.doesNotMatch(snapshot, /private-value|private-password|private=excluded|record-private-id|private-filter/);
  assert.equal(JSON.parse(snapshot).report.renderedControls.some((row) => row.id === 'password'), false);
  fs.writeFileSync(path.join(fx.portal, 'content-snippets/Banner.contentsnippet.value.html'), 'Updated banner');
  await scope.locator('[data-act="inspect-refresh"]').click();
  await scope.locator('[data-group="runtime-snippets"]').getByText('“Updated banner”').waitFor();
  await page.locator('#other').click();
  await scope.locator('[data-act="tab"][data-v="runtime"]').click();
  await scope.getByText('Other', { exact: false }).first().waitFor();
  assert.equal(panel.stateFor(page).inspection.path, '/other/');
  assert.equal(requests.some((route) => route.startsWith('/_sim/') || route.startsWith('/__sim/')), false);
  assert.deepEqual(errors, []);
});
