// Liquid resource strings (resx) per culture for the keys the mirage defines in lib/liquid.mjs
// (RESX), from the MIT-licensed Adxstudio resource files
// (Adxstudio.Xrm.Resources/ResourceFiles/strings.<culture>.resx). Generated; English values live in
// lib/liquid.mjs, where values observed on the live portal win over the resource file.
// Copyright (c) Microsoft Corporation. Licensed under the MIT License.
export const RESX_CULTURES = Object.freeze({
  "bg-BG": Object.freeze({
    Sign_In: "Влизане",
    Sign_Out: "Излизане",
    Profile: "Профил",
    Search_DefaultText: "Търсене",
    Discover_Contoso: "Запознайте се с Contoso",
    Toggle_Navigation: "Превключване на навигацията",
    Editable_Cancel_Label: "Отказ",
    Submit_Button_Label_Text: "Подаване",
    Poll_Results_Label: "Преглед на резултатите",
    Poll_Totals_Label: "Общ брой гласове:",
    Poll_Return_Label: "Връщане към анкетата",
    Poll_Archives_Heading: "Архиви на анкети",
    Poll_DefaultText: "Анкета",
    All: "Всички",
    Search_Filter: "Филтър за търсене",
    Search_No_Results_Found: "Не са открити резултати за тази заявка: ",
    Search_Results_Format_String: "Резултати {0} – {1} от {2} за заявка: ",
    Most_Popular_Categories: "Най-популярни категории",
    Most_Recent_Categories: "Най-нови категории",
    Events_Label: "Събития",
    Forums_Label: "Форуми",
    Issues_Label: "Проблеми",
    KnowledgeMgmt_Most_Popular_Articles: "Най-популярни статии",
    KnowledgeMgmt_Most_Recent_Articles: "Най-нови статии",
    Knowledge_Base_Label: "База знания",
    Knowledge_Article_Unavailable: "Статията е недостъпна",
    Browse_The_KB: "Преглед на БЗ",
    Popular_Topics: "Популярни теми",
    Related_Categories_DefaultText: "Свързани категории",
    Get_Help_DefaultText: "Получаване на помощ",
    Find_Your_Product: "Търсене на вашия продукт",
    View_More: "Преглед на още",
    Most_Popular: "Най-популярни",
    Top_Rated_Articles: "Статии с най-високи оценки",
    Case_Deflection_Suggested_Topics: "Предлагани теми",
    Sorting_Rating: "Средни оценки на потребител",
    Sorting_Relevance: "Съответствие",
    Sorting_ViewCount: "Брой преглеждания",
    Sorting_Options: "Опции за сортиране",
    Facet_RecordType: "Тип на записа",
    Facet_DateModified: "Променена дата",
    Facet_Show_Less: "Показване на по-малко",
    Facet_Show_More: "Показване на повече",
    Facet_All: "Всички",
    Facet_Rating: "Оценка",
    Facet_Products: "Продукти",
    Pagination_Current_Page: "Текуща страница {0}",
    Pagination_First_Page: "Първа страница",
    Pagination_Last_Page: "Последна страница",
    Pagination_Next_Page: "Следваща страница",
    Pagination_Page: "Страница {0}",
    Pagination_Previous_Page: "Предишна страница",
  }),
  "ca-ES": Object.freeze({
    Sign_In: "Inicia la sessió",
    Sign_Out: "Tanca la sessió",
    Profile: "Perfil;",
    Search_DefaultText: "Cerca",
    Discover_Contoso: "Descobriu Contoso",
    Toggle_Navigation: "Commuta la navegació",
    Editable_Cancel_Label: "Cancel·la",
    Submit_Button_Label_Text: "Envia",
    Poll_Results_Label: "Visualitza els resultats",
    Poll_Totals_Label: "Vots totals:",
    Poll_Return_Label: "Torna al sondeig",
    Poll_Archives_Heading: "Arxivaments de sondeig",
    Poll_DefaultText: "Sondeig",
    All: "Tot",
    Search_Filter: "Filtre de cerca",
    Search_No_Results_Found: "No s'han trobat resultats per a aquesta consulta: ",
    Search_Results_Format_String: "Resultats {0} - {1} de {2} per a la consulta: ",
    Most_Popular_Categories: "Categories més populars",
    Most_Recent_Categories: "Categories més recents",
    Events_Label: "Incidències",
    Forums_Label: "Fòrums",
    Issues_Label: "Problemes",
    KnowledgeMgmt_Most_Popular_Articles: "Articles més populars",
    KnowledgeMgmt_Most_Recent_Articles: "Articles més recents",
    Knowledge_Base_Label: "Knowledge Base",
    Knowledge_Article_Unavailable: "Article no disponible",
    Browse_The_KB: "Examina la KB",
    Popular_Topics: "Temes populars",
    Related_Categories_DefaultText: "Categories relacionades",
    Get_Help_DefaultText: "Obtén ajuda",
    Find_Your_Product: "Cerca el vostre producte",
    View_More: "Visualitza'n més",
    Most_Popular: "Més populars",
    Top_Rated_Articles: "Articles amb valoració més alta",
    Case_Deflection_Suggested_Topics: "Temes suggerits",
    Sorting_Rating: "Valoracions mitjanes del usuaris",
    Sorting_Relevance: "Rellevància",
    Sorting_ViewCount: "Recompte de visualitzacions",
    Sorting_Options: "Opcions d'ordenació",
    Facet_RecordType: "Tipus de registre",
    Facet_DateModified: "Data de modificació",
    Facet_Show_Less: "Mostra'n menys",
    Facet_Show_More: "Mostra'n més",
    Facet_All: "Tot",
    Facet_Rating: "Valoració",
    Facet_Products: "Productes",
    Pagination_Current_Page: "Pàgina actual {0}",
    Pagination_First_Page: "Primera pàgina",
    Pagination_Last_Page: "Última pàgina",
    Pagination_Next_Page: "Pàgina següent",
    Pagination_Page: "Pàgina {0}",
    Pagination_Previous_Page: "Pàgina anterior",
  }),
  "cs-CZ": Object.freeze({
    Sign_In: "Přihlásit se",
    Sign_Out: "Odhlásit se",
    Profile: "Profil;",
    Search_DefaultText: "Hledat",
    Discover_Contoso: "Objevte Contoso",
    Toggle_Navigation: "Přepnout navigaci",
    Editable_Cancel_Label: "Zrušit",
    Submit_Button_Label_Text: "Odeslat",
    Poll_Results_Label: "Zobrazit výsledky",
    Poll_Totals_Label: "Celkový počet hlasů:",
    Poll_Return_Label: "Návrat k hlasování",
    Poll_Archives_Heading: "Archivy hlasování",
    Poll_DefaultText: "Hlasování",
    All: "Vše",
    Search_Filter: "Filtr hledání",
    Search_No_Results_Found: "Pro tento dotaz se nenašly žádné výsledky: ",
    Search_Results_Format_String: "Výsledky {0} – {1} z {2} pro dotaz: ",
    Most_Popular_Categories: "Nejoblíbenější kategorie",
    Most_Recent_Categories: "Nejnovější kategorie",
    Events_Label: "Události",
    Forums_Label: "Fóra",
    Issues_Label: "Problémy",
    KnowledgeMgmt_Most_Popular_Articles: "Nejoblíbenější články",
    KnowledgeMgmt_Most_Recent_Articles: "Nejnovější články",
    Knowledge_Base_Label: "Znalostní báze",
    Knowledge_Article_Unavailable: "Článek je nedostupný",
    Browse_The_KB: "Procházet znalostní bázi",
    Popular_Topics: "Oblíbená témata",
    Related_Categories_DefaultText: "Související kategorie",
    Get_Help_DefaultText: "Získat nápovědu",
    Find_Your_Product: "Vyhledat váš produkt",
    View_More: "Zobrazit více",
    Most_Popular: "Nejoblíbenější",
    Top_Rated_Articles: "Nejlépe hodnocené články",
    Case_Deflection_Suggested_Topics: "Doporučená témata",
    Sorting_Rating: "Průměrné uživatelské hodnocení",
    Sorting_Relevance: "Relevance",
    Sorting_ViewCount: "Počet zobrazení",
    Sorting_Options: "Možnosti řazení",
    Facet_RecordType: "Typ záznamu",
    Facet_DateModified: "Datum úprav",
    Facet_Show_Less: "Zobrazit méně",
    Facet_Show_More: "Zobrazit více",
    Facet_All: "Vše",
    Facet_Rating: "Hodnocení",
    Facet_Products: "Produkty",
    Pagination_Current_Page: "Aktuální stránka {0}",
    Pagination_First_Page: "První stránka",
    Pagination_Last_Page: "Poslední stránka",
    Pagination_Next_Page: "Další stránka",
    Pagination_Page: "Stránka {0}",
    Pagination_Previous_Page: "Předchozí stránka",
  }),
  "da-DK": Object.freeze({
    Sign_In: "Log på",
    Sign_Out: "Log af",
    Profile: "Profil:",
    Search_DefaultText: "Søg",
    Discover_Contoso: "Udforsk Contoso",
    Toggle_Navigation: "Slå navigation til/fra",
    Editable_Cancel_Label: "Annuller",
    Submit_Button_Label_Text: "Send",
    Poll_Results_Label: "Vis resultater",
    Poll_Totals_Label: "Samlede stemmer:",
    Poll_Return_Label: "Tilbage til afstemning",
    Poll_Archives_Heading: "Afstemningsarkiver",
    Poll_DefaultText: "Afstemning",
    All: "Alle",
    Search_Filter: "Søgefilter",
    Search_No_Results_Found: "Der blev ikke fundet nogen resultater for denne forespørgsel: ",
    Search_Results_Format_String: "Resultat {0} - {1} af {2} for forespørgslen: ",
    Most_Popular_Categories: "Mest populære kategorier",
    Most_Recent_Categories: "Seneste kategorier",
    Events_Label: "Hændelser",
    Forums_Label: "Forummer",
    Issues_Label: "Problemer",
    KnowledgeMgmt_Most_Popular_Articles: "Mest populære artikler",
    KnowledgeMgmt_Most_Recent_Articles: "Seneste artikler",
    Knowledge_Base_Label: "Videnbase",
    Knowledge_Article_Unavailable: "Artikel ikke tilgængelig",
    Browse_The_KB: "Gennemse videnbasen",
    Popular_Topics: "Populære emner",
    Related_Categories_DefaultText: "Relaterede kategorier",
    Get_Help_DefaultText: "Få hjælp",
    Find_Your_Product: "Find dit produkt",
    View_More: "Vis flere",
    Most_Popular: "Mest populære",
    Top_Rated_Articles: "Bedst bedømte artikler",
    Case_Deflection_Suggested_Topics: "Foreslåede emner",
    Sorting_Rating: "Gennemsnitlig brugerklassificeringer",
    Sorting_Relevance: "Relevans",
    Sorting_ViewCount: "Visningsantal",
    Sorting_Options: "Sorteringsindstillinger",
    Facet_RecordType: "Posttype",
    Facet_DateModified: "Ændrindgsdato",
    Facet_Show_Less: "Vis mindre",
    Facet_Show_More: "Vis mere",
    Facet_All: "Alle",
    Facet_Rating: "Klassificering",
    Facet_Products: "Produkter",
    Pagination_Current_Page: "Aktuel side {0}",
    Pagination_First_Page: "Første side",
    Pagination_Last_Page: "Sidste side",
    Pagination_Next_Page: "Næste side",
    Pagination_Page: "Side {0}",
    Pagination_Previous_Page: "Forrige side",
  }),
  "de-DE": Object.freeze({
    Sign_In: "Anmelden",
    Sign_Out: "Abmelden",
    Profile: "Profil;",
    Search_DefaultText: "Suchen",
    Discover_Contoso: "Entdecken Sie Contoso",
    Toggle_Navigation: "Navigation umschalten",
    Editable_Cancel_Label: "Abbrechen",
    Submit_Button_Label_Text: "Übermitteln",
    Poll_Results_Label: "Ergebnisse anzeigen",
    Poll_Totals_Label: "Gesamte Stimmen:",
    Poll_Return_Label: "Zurück zur Umfrage",
    Poll_Archives_Heading: "Umfragearchive",
    Poll_DefaultText: "Umfrage",
    All: "Alle",
    Search_Filter: "Suchfilter",
    Search_No_Results_Found: "Für diese Abfrage wurden keine Ergebnisse gefunden: ",
    Search_Results_Format_String: "Ergebnisse {0}–{1} von {2} für Abfrage: ",
    Most_Popular_Categories: "Beliebteste Kategorien",
    Most_Recent_Categories: "Neueste Kategorien",
    Events_Label: "Ereignisse",
    Forums_Label: "Foren",
    Issues_Label: "Probleme",
    KnowledgeMgmt_Most_Popular_Articles: "Beliebteste Artikel",
    KnowledgeMgmt_Most_Recent_Articles: "Neueste Artikel",
    Knowledge_Base_Label: "Wissensdatenbank",
    Knowledge_Article_Unavailable: "Artikel ist nicht verfügbar",
    Browse_The_KB: "Wissensdatenbank durchsuchen",
    Popular_Topics: "Beliebte Themen",
    Related_Categories_DefaultText: "Zugehörige Kategorien",
    Get_Help_DefaultText: "Hilfe",
    Find_Your_Product: "Ihr Produkt suchen",
    View_More: "Mehr anzeigen",
    Most_Popular: "Beliebteste Artikel",
    Top_Rated_Articles: "Am besten bewertete Artikel",
    Case_Deflection_Suggested_Topics: "Vorgeschlagene Themen",
    Sorting_Rating: "Durchschnittliche Nutzerbewertung",
    Sorting_Relevance: "Relevanz",
    Sorting_ViewCount: "Anzahl angezeigt",
    Sorting_Options: "Sortierungssoptionen",
    Facet_RecordType: "Datensatztyp",
    Facet_DateModified: "Änderungsdatum",
    Facet_Show_Less: "Weniger anzeigen",
    Facet_Show_More: "Mehr anzeigen",
    Facet_All: "Alle",
    Facet_Rating: "Bewertung",
    Facet_Products: "Produkte",
    Pagination_Current_Page: "Aktuelle Seite {0}",
    Pagination_First_Page: "Erste Seite",
    Pagination_Last_Page: "Letzte Seite",
    Pagination_Next_Page: "Nächste Seite",
    Pagination_Page: "Seite {0}",
    Pagination_Previous_Page: "Vorherige Seite",
  }),
  "el-GR": Object.freeze({
    Sign_In: "Είσοδος",
    Sign_Out: "Έξοδος",
    Profile: "Προφίλ,",
    Search_DefaultText: "Αναζήτηση",
    Discover_Contoso: "Ανακαλύψτε την Contoso",
    Toggle_Navigation: "Εναλλαγή περιήγησης",
    Editable_Cancel_Label: "Άκυρο",
    Submit_Button_Label_Text: "Υποβολή",
    Poll_Results_Label: "Προβολή αποτελεσμάτων",
    Poll_Totals_Label: "Συνολικές ψήφοι:",
    Poll_Return_Label: "Επιστροφή στη σφυγμομέτρηση",
    Poll_Archives_Heading: "Αρχειοθήκες σφυγμομέτρησης",
    Poll_DefaultText: "Ανίχνευση",
    All: "Όλα",
    Search_Filter: "Φίλτρο αναζήτησης",
    Search_No_Results_Found: "Δεν βρέθηκαν αποτελέσματα για αυτό το ερώτημα: ",
    Search_Results_Format_String: "Αποτελέσματα {0} - {1} από {2} για το ερώτημα: ",
    Most_Popular_Categories: "Δημοφιλέστερες κατηγορίες",
    Most_Recent_Categories: "Οι πιο πρόσφατες κατηγορίες",
    Events_Label: "Συμβάντα",
    Forums_Label: "Φόρουμ",
    Issues_Label: "Ζητήματα",
    KnowledgeMgmt_Most_Popular_Articles: "Δημοφιλέστερα άρθρα",
    KnowledgeMgmt_Most_Recent_Articles: "Τα πιο πρόσφατα άρθρα",
    Knowledge_Base_Label: "Γνωσιακή βάση",
    Knowledge_Article_Unavailable: "Μη διαθέσιμο άρθρο",
    Browse_The_KB: "Αναζήτηση στη Γνωσιακή βάση",
    Popular_Topics: "Δημοφιλή θέματα",
    Related_Categories_DefaultText: "Σχετικές κατηγορίες",
    Get_Help_DefaultText: "Λήψη βοήθειας",
    Find_Your_Product: "Εύρεση του προϊόντος σας",
    View_More: "Προβολή περισσότερων",
    Most_Popular: "Τα πιο δημοφιλή",
    Top_Rated_Articles: "Κορυφαία άρθρα",
    Case_Deflection_Suggested_Topics: "Προτεινόμενα θέματα",
    Sorting_Rating: "Μέσος όρος αξιολογήσεων χρηστών",
    Sorting_Relevance: "Συνάφεια",
    Sorting_ViewCount: "Πλήθος προβολών",
    Sorting_Options: "Επιλογές ταξινόμησης",
    Facet_RecordType: "Τύπος καρτέλας",
    Facet_DateModified: "Ημερομηνία τροποποίησης",
    Facet_Show_Less: "Εμφάνιση λιγότερων",
    Facet_Show_More: "Εμφάνιση περισσότερων",
    Facet_All: "Όλα",
    Facet_Rating: "Αξιολόγηση",
    Facet_Products: "Προϊόντα",
    Pagination_Current_Page: "Τρέχουσα σελίδα {0}",
    Pagination_First_Page: "Πρώτη σελίδα",
    Pagination_Last_Page: "Τελευταία σελίδα",
    Pagination_Next_Page: "Επόμενη σελίδα",
    Pagination_Page: "Σελίδα {0}",
    Pagination_Previous_Page: "Προηγούμενη σελίδα",
  }),
  "es-ES": Object.freeze({
    Sign_In: "Iniciar sesión",
    Sign_Out: "Cerrar sesión",
    Profile: "Perfil;",
    Search_DefaultText: "Búsqueda",
    Discover_Contoso: "Descubra Contoso",
    Toggle_Navigation: "Alternar navegación",
    Editable_Cancel_Label: "Cancelar",
    Submit_Button_Label_Text: "Enviar",
    Poll_Results_Label: "Ver resultados",
    Poll_Totals_Label: "Votos totales:",
    Poll_Return_Label: "Volver al sondeo",
    Poll_Archives_Heading: "Archivos de sondeos",
    Poll_DefaultText: "Sondeo",
    All: "Todo",
    Search_Filter: "Filtro de búsqueda",
    Search_No_Results_Found: "No se encontraron resultados para esta consulta: ",
    Search_Results_Format_String: "Resultados {0} - {1} de {2} de la consulta: ",
    Most_Popular_Categories: "Categorías más populares",
    Most_Recent_Categories: "Categorías más recientes",
    Events_Label: "Eventos",
    Forums_Label: "Foros",
    Issues_Label: "Problemas",
    KnowledgeMgmt_Most_Popular_Articles: "Artículos más populares",
    KnowledgeMgmt_Most_Recent_Articles: "Artículos más recientes",
    Knowledge_Base_Label: "Knowledge Base",
    Knowledge_Article_Unavailable: "Artículo no disponible",
    Browse_The_KB: "Examinar la KB",
    Popular_Topics: "Temas populares",
    Related_Categories_DefaultText: "Categorías relacionadas",
    Get_Help_DefaultText: "Obtener Ayuda",
    Find_Your_Product: "Buscar su producto",
    View_More: "Ver más",
    Most_Popular: "Más populares",
    Top_Rated_Articles: "Artículos con la clasificación más alta",
    Case_Deflection_Suggested_Topics: "Temas sugeridos",
    Sorting_Rating: "Valoraciones medias de los usuarios",
    Sorting_Relevance: "Relevancia",
    Sorting_ViewCount: "Número de visualizaciones",
    Sorting_Options: "Opciones de ordenación",
    Facet_RecordType: "Tipo de registro",
    Facet_DateModified: "Fecha de modificación",
    Facet_Show_Less: "Mostrar menos",
    Facet_Show_More: "Mostrar más",
    Facet_All: "Todo",
    Facet_Rating: "Valoración",
    Facet_Products: "Productos",
    Pagination_Current_Page: "Página actual {0}",
    Pagination_First_Page: "Primera página",
    Pagination_Last_Page: "Última página",
    Pagination_Next_Page: "Página siguiente",
    Pagination_Page: "Página {0}",
    Pagination_Previous_Page: "Página anterior",
  }),
  "et-EE": Object.freeze({
    Sign_In: "Sisselogimine",
    Sign_Out: "Logi välja",
    Profile: "Profiil;",
    Search_DefaultText: "Otsing",
    Discover_Contoso: "Avastage Contoso",
    Toggle_Navigation: "Lülita navigeerimine sisse/välja",
    Editable_Cancel_Label: "Tühista",
    Submit_Button_Label_Text: "Edastamine",
    Poll_Results_Label: "Kuva tulemid",
    Poll_Totals_Label: "Hääli kokku:",
    Poll_Return_Label: "Tagasi küsitluse juurde",
    Poll_Archives_Heading: "Küsitluste arhiivid",
    Poll_DefaultText: "Küsitlus",
    All: "Kõik",
    Search_Filter: "Otsingufilter",
    Search_No_Results_Found: "Selle päringu tulemusi ei leitud: ",
    Search_Results_Format_String: "Tulemid {0}–{1}/{2} päringule: ",
    Most_Popular_Categories: "Kõige populaarsemad kategooriad",
    Most_Recent_Categories: "Kõige uuemad kategooriad",
    Events_Label: "Sündmused",
    Forums_Label: "Foorumid",
    Issues_Label: "Probleemid",
    KnowledgeMgmt_Most_Popular_Articles: "Kõige populaarsemad artiklid",
    KnowledgeMgmt_Most_Recent_Articles: "Kõige uuemad artiklid",
    Knowledge_Base_Label: "Teabebaas",
    Knowledge_Article_Unavailable: "Artikkel pole saadaval",
    Browse_The_KB: "Sirvi teabebaasi",
    Popular_Topics: "Populaarsemad teemad",
    Related_Categories_DefaultText: "Seostuvad kategooriad",
    Get_Help_DefaultText: "Spikker",
    Find_Your_Product: "Leidke oma toode",
    View_More: "Kuva rohkem",
    Most_Popular: "Kõige populaarsem",
    Top_Rated_Articles: "Parima hinnanguga artiklid",
    Case_Deflection_Suggested_Topics: "Soovitatud teemad",
    Sorting_Rating: "Keskmised kasutajahinnangud",
    Sorting_Relevance: "Asjakohasus",
    Sorting_ViewCount: "Vaatamiste arv",
    Sorting_Options: "Sortimisvalikud",
    Facet_RecordType: "Kirje tüüp",
    Facet_DateModified: "Muutmiskuupäev",
    Facet_Show_Less: "Kuva vähem",
    Facet_Show_More: "Kuva rohkem",
    Facet_All: "Kõik",
    Facet_Rating: "Hinnang",
    Facet_Products: "Tooted",
    Pagination_Current_Page: "Praegune leht {0}",
    Pagination_First_Page: "Esimene leht",
    Pagination_Last_Page: "Viimane leht",
    Pagination_Next_Page: "Järgmine leht",
    Pagination_Page: "Leht {0}",
    Pagination_Previous_Page: "Eelmine leht",
  }),
  "eu-ES": Object.freeze({
    Sign_In: "Hasi saioa",
    Sign_Out: "Amaitu saioa",
    Profile: "Profila;",
    Search_DefaultText: "Bilatu",
    Discover_Contoso: "Ezagutu Contoso",
    Toggle_Navigation: "Aldatu nabigazioa",
    Editable_Cancel_Label: "Utzi",
    Submit_Button_Label_Text: "Bidali",
    Poll_Results_Label: "Ikusi emaitzak",
    Poll_Totals_Label: "Botoak, guztira:",
    Poll_Return_Label: "Itzuli galdeketara",
    Poll_Archives_Heading: "Galdeketa-artxiboak",
    Poll_DefaultText: "Galdeketa",
    All: "Guztiak",
    Search_Filter: "Bilaketa-iragazkia",
    Search_No_Results_Found: "Ez da aurkitu kontsulta honen emaitzarik: ",
    Search_Results_Format_String: "Kontsulta honen {0}-{1}/{2} emaitzak: ",
    Most_Popular_Categories: "Kategoria ezagunenak",
    Most_Recent_Categories: "Azken kategoriak",
    Events_Label: "Gertaerak",
    Forums_Label: "Foroak",
    Issues_Label: "Arazoak",
    KnowledgeMgmt_Most_Popular_Articles: "Artikulu ezagunenak",
    KnowledgeMgmt_Most_Recent_Articles: "Azken artikuluak",
    Knowledge_Base_Label: "Knowledge Base",
    Knowledge_Article_Unavailable: "Artikulua ez dago erabilgarri",
    Browse_The_KB: "Arakatu KBa",
    Popular_Topics: "Gai ezagunak",
    Related_Categories_DefaultText: "Erlazionatutako kategoriak",
    Get_Help_DefaultText: "Lortu laguntza",
    Find_Your_Product: "Bilatu produktua",
    View_More: "Ikusi gehiago",
    Most_Popular: "Ezagunenak",
    Top_Rated_Articles: "Hoberen baloratutako artikuluak",
    Case_Deflection_Suggested_Topics: "Iradokitako gaiak",
    Sorting_Rating: "Erabiltzaileen batez besteko balorazioak",
    Sorting_Relevance: "Egokitasuna",
    Sorting_ViewCount: "Ikustaldi kopurua",
    Sorting_Options: "Ordenatzeko aukerak",
    Facet_RecordType: "Erregistro mota",
    Facet_DateModified: "Aldaketa-data",
    Facet_Show_Less: "Erakutsi gutxiago",
    Facet_Show_More: "Erakutsi gehiago",
    Facet_All: "Denak",
    Facet_Rating: "Balorazioa",
    Facet_Products: "Produktuak",
    Pagination_Current_Page: "Uneko orria: {0}. orria",
    Pagination_First_Page: "Lehen orria",
    Pagination_Last_Page: "Azken orria",
    Pagination_Next_Page: "Hurrengo orria",
    Pagination_Page: "{0}. orria",
    Pagination_Previous_Page: "Aurreko orria",
  }),
  "fi-FI": Object.freeze({
    Sign_In: "Kirjaudu sisään",
    Sign_Out: "Kirjaudu ulos",
    Profile: "Profiili;",
    Search_DefaultText: "Haku",
    Discover_Contoso: "Tutustu Contosoon",
    Toggle_Navigation: "Vaihda siirtymistä",
    Editable_Cancel_Label: "Peruuta",
    Submit_Button_Label_Text: "Lähetä",
    Poll_Results_Label: "Näytä tulokset",
    Poll_Totals_Label: "Ääniä yhteensä:",
    Poll_Return_Label: "Palaa kyselyyn",
    Poll_Archives_Heading: "Kyselyarkistot",
    Poll_DefaultText: "Kysely",
    All: "Kaikki",
    Search_Filter: "Hakusuodatin",
    Search_No_Results_Found: "Seuraavalle kyselylle ei löytynyt tuloksia: ",
    Search_Results_Format_String: "Seuraavan kyselyn tulokset {0}–{1}/{2}: ",
    Most_Popular_Categories: "Suosituimmat luokat",
    Most_Recent_Categories: "Uusimmat luokat",
    Events_Label: "Tapahtumat",
    Forums_Label: "Keskustelupalstat",
    Issues_Label: "Ongelmat",
    KnowledgeMgmt_Most_Popular_Articles: "Suosituimmat artikkelit",
    KnowledgeMgmt_Most_Recent_Articles: "Uusimmat artikkelit",
    Knowledge_Base_Label: "Tietokanta",
    Knowledge_Article_Unavailable: "Artikkeli ei ole käytettävissä",
    Browse_The_KB: "Selaa tietokantaa",
    Popular_Topics: "Suositut aiheet",
    Related_Categories_DefaultText: "Liittyvät luokat",
    Get_Help_DefaultText: "Hae ohjeita",
    Find_Your_Product: "Etsi tuote",
    View_More: "Näytä lisää",
    Most_Popular: "Suosituimmat",
    Top_Rated_Articles: "Parhaiksi arvioidut artikkelit",
    Case_Deflection_Suggested_Topics: "Ehdotetut aiheet",
    Sorting_Rating: "Keskimääräiset käyttäjäluokitukset",
    Sorting_Relevance: "Osuvuus",
    Sorting_ViewCount: "Näyttökertojen määrä",
    Sorting_Options: "Lajitteluvaihtoehdot",
    Facet_RecordType: "Tietuetyyppi",
    Facet_DateModified: "Muokkauspäivä",
    Facet_Show_Less: "Näytä vähemmän",
    Facet_Show_More: "Näytä enemmän",
    Facet_All: "Kaikki",
    Facet_Rating: "Luokittelu",
    Facet_Products: "Tuotteet",
    Pagination_Current_Page: "Nykyinen sivu {0}",
    Pagination_First_Page: "Ensimmäinen sivu",
    Pagination_Last_Page: "Viimeinen sivu",
    Pagination_Next_Page: "Seuraava sivu",
    Pagination_Page: "Sivu {0}",
    Pagination_Previous_Page: "Edellinen sivu",
  }),
  "fr-FR": Object.freeze({
    Sign_In: "Se connecter",
    Sign_Out: "Se déconnecter",
    Profile: "Profil ;",
    Search_DefaultText: "Rechercher",
    Discover_Contoso: "Découvrez Contoso",
    Toggle_Navigation: "Activer/Désactiver la navigation",
    Editable_Cancel_Label: "Annuler",
    Submit_Button_Label_Text: "Envoyer",
    Poll_Results_Label: "Afficher les résultats",
    Poll_Totals_Label: "Nombre total de votes :",
    Poll_Return_Label: "Revenir au sondage",
    Poll_Archives_Heading: "Archives de sondages",
    Poll_DefaultText: "Sondage",
    All: "Tous",
    Search_Filter: "Filtre de recherche",
    Search_No_Results_Found: "Aucun résultat n'a été trouvé pour cette requête : ",
    Search_Results_Format_String: "Résultats {0} - {1} sur {2} pour la requête : ",
    Most_Popular_Categories: "Catégories les plus populaires",
    Most_Recent_Categories: "Catégories les plus récentes",
    Events_Label: "Événements",
    Forums_Label: "Forums",
    Issues_Label: "Problèmes",
    KnowledgeMgmt_Most_Popular_Articles: "Articles les plus populaires",
    KnowledgeMgmt_Most_Recent_Articles: "Articles les plus récents",
    Knowledge_Base_Label: "Base de connaissances",
    Knowledge_Article_Unavailable: "Article indisponible",
    Browse_The_KB: "Parcourir la base de connaissances",
    Popular_Topics: "Sujets populaires",
    Related_Categories_DefaultText: "Catégories associées",
    Get_Help_DefaultText: "Obtenir de l'aide",
    Find_Your_Product: "Rechercher votre produit",
    View_More: "Afficher plus",
    Most_Popular: "Les plus populaires",
    Top_Rated_Articles: "Articles les mieux classés",
    Case_Deflection_Suggested_Topics: "Sujets suggérés",
    Sorting_Rating: "Évaluations utilisateur standard",
    Sorting_Relevance: "Pertinence",
    Sorting_ViewCount: "Nombre de vues",
    Sorting_Options: "Options de tri",
    Facet_RecordType: "Type d’enregistrement",
    Facet_DateModified: "Date modifiée",
    Facet_Show_Less: "Afficher moins",
    Facet_Show_More: "Afficher plus",
    Facet_All: "Tous",
    Facet_Rating: "Classement",
    Facet_Products: "Produits",
    Pagination_Current_Page: "Page actuelle {0}",
    Pagination_First_Page: "Première page",
    Pagination_Last_Page: "Dernière page",
    Pagination_Next_Page: "Page suivante",
    Pagination_Page: "Page {0}",
    Pagination_Previous_Page: "Page précédente",
  }),
  "gl-ES": Object.freeze({
    Sign_In: "Iniciar sesión",
    Sign_Out: "Pechar sesión",
    Profile: "Perfil;",
    Search_DefaultText: "Buscar",
    Discover_Contoso: "Detectar Contoso",
    Toggle_Navigation: "Alternar navegación",
    Editable_Cancel_Label: "Cancelar",
    Submit_Button_Label_Text: "Enviar",
    Poll_Results_Label: "Visualizar resultados",
    Poll_Totals_Label: "Número total de votos:",
    Poll_Return_Label: "Volver á enquisa",
    Poll_Archives_Heading: "Arquivos da enquisa",
    Poll_DefaultText: "Enquisa",
    All: "Todo",
    Search_Filter: "Buscar filtro",
    Search_No_Results_Found: "Non se atoparon resultados para esta consulta: ",
    Search_Results_Format_String: "Resultados {0} - {1} de {2} para a consulta: ",
    Most_Popular_Categories: "Categorías máis populares",
    Most_Recent_Categories: "Categorías máis recentes",
    Events_Label: "Eventos",
    Forums_Label: "Foros",
    Issues_Label: "Problemas",
    KnowledgeMgmt_Most_Popular_Articles: "Artigos máis populares",
    KnowledgeMgmt_Most_Recent_Articles: "Artigos máis recentes",
    Knowledge_Base_Label: "Knowledge Base",
    Knowledge_Article_Unavailable: "Artigo non dispoñible",
    Browse_The_KB: "Explorar a KB",
    Popular_Topics: "Temas populares",
    Related_Categories_DefaultText: "Categorías relacionadas",
    Get_Help_DefaultText: "Obter axuda",
    Find_Your_Product: "Buscar o seu produto",
    View_More: "Ver máis",
    Most_Popular: "Máis populares",
    Top_Rated_Articles: "Artigos mellor valorados",
    Case_Deflection_Suggested_Topics: "Temas suxeridos",
    Sorting_Rating: "Valoracións de usuarios medias",
    Sorting_Relevance: "Relevancia",
    Sorting_ViewCount: "Número de visualizacións",
    Sorting_Options: "Opcións de ordenación",
    Facet_RecordType: "Tipo de rexistro",
    Facet_DateModified: "Data modificada",
    Facet_Show_Less: "Mostrar menos",
    Facet_Show_More: "Mostrar máis",
    Facet_All: "Todos",
    Facet_Rating: "Valoración",
    Facet_Products: "Produtos",
    Pagination_Current_Page: "Páxina actual {0}",
    Pagination_First_Page: "Primeira páxina",
    Pagination_Last_Page: "Última páxina",
    Pagination_Next_Page: "Páxina seguinte",
    Pagination_Page: "Páxina {0}",
    Pagination_Previous_Page: "Páxina anterior",
  }),
  "hi-IN": Object.freeze({
    Sign_In: "साइन इन करें",
    Sign_Out: "साइन आउट करें",
    Profile: "प्रोफ़ाइल;",
    Search_DefaultText: "खोजें",
    Discover_Contoso: "Contoso का अन्वेषण करें",
    Toggle_Navigation: "नेविगेशन टॉगल करें",
    Editable_Cancel_Label: "रद्द करें",
    Submit_Button_Label_Text: "सबमिट करें",
    Poll_Results_Label: "परिणाम देखें",
    Poll_Totals_Label: "कुल वोट्स:",
    Poll_Return_Label: "पोल पर लौटें",
    Poll_Archives_Heading: "पोल संग्रह",
    Poll_DefaultText: "पोल",
    All: "सभी",
    Search_Filter: "खोज फ़ि‍ल्‍टर",
    Search_No_Results_Found: "इस क्वेरी के लिए कोई परिणाम नहीं मिले: ",
    Search_Results_Format_String: "क्वेरी के लिए परिणाम {0} - {2} में से {1}: ",
    Most_Popular_Categories: "सबसे लोकप्रिय श्रेणियाँ",
    Most_Recent_Categories: "सबसे नवीनतम श्रेणियाँ",
    Events_Label: "इवेंट्स",
    Forums_Label: "फ़ोरम",
    Issues_Label: "समस्याएँ",
    KnowledgeMgmt_Most_Popular_Articles: "सबसे लोकप्रिय आलेख",
    KnowledgeMgmt_Most_Recent_Articles: "सबसे नवीनतम आलेख",
    Knowledge_Base_Label: "नॉलेज बेस",
    Knowledge_Article_Unavailable: "आलेख अनुपलब्ध",
    Browse_The_KB: "KB ब्राउज़ करें",
    Popular_Topics: "लोकप्रिय विषय",
    Related_Categories_DefaultText: "संबंधित श्रेणियाँ",
    Get_Help_DefaultText: "मदद प्राप्त करें",
    Find_Your_Product: "अपना उत्पाद ढूँढें",
    View_More: "अधिक देखें",
    Most_Popular: "सबसे लोकप्रिय",
    Top_Rated_Articles: "शीर्ष मूल्यांकित आलेख",
    Case_Deflection_Suggested_Topics: "सुझाए गए विषय",
    Sorting_Rating: "औसत उपयोगकर्ता रेटिंग",
    Sorting_Relevance: "प्रासंगिकता",
    Sorting_ViewCount: "संख्‍या देखें",
    Sorting_Options: "सॉर्टिंग विकल्प",
    Facet_RecordType: "रिकॉर्ड प्रकार",
    Facet_DateModified: "संशोधन दिनांक",
    Facet_Show_Less: "कम दिखाएँ",
    Facet_Show_More: "अधिक दिखाएँ",
    Facet_All: "सभी",
    Facet_Rating: "रेटिंग",
    Facet_Products: "उत्पाद",
    Pagination_Current_Page: "वर्तमान पृष्ठ {0}",
    Pagination_First_Page: "प्रथम पृष्ठ",
    Pagination_Last_Page: "अंतिम पृष्ठ",
    Pagination_Next_Page: "अगला पृष्ठ",
    Pagination_Page: "पृष्ठ {0}",
    Pagination_Previous_Page: "पिछला पृष्ठ",
  }),
  "hr-HR": Object.freeze({
    Sign_In: "Prijava",
    Sign_Out: "Odjava",
    Profile: "Profil;",
    Search_DefaultText: "Pretraživanje",
    Discover_Contoso: "Otkrijte Contoso",
    Toggle_Navigation: "Uključivanje/isključivanje navigacije",
    Editable_Cancel_Label: "Odustani",
    Submit_Button_Label_Text: "Pošalji",
    Poll_Results_Label: "Prikaz rezultata",
    Poll_Totals_Label: "Ukupno glasova:",
    Poll_Return_Label: "Povratak na anketu",
    Poll_Archives_Heading: "Arhiv anketa",
    Poll_DefaultText: "Anketa",
    All: "Sve",
    Search_Filter: "Pretraži filtar",
    Search_No_Results_Found: "Nisu pronađeni rezultati za ovaj upit: ",
    Search_Results_Format_String: "Rezultati {0} – {1} od {2} za upit: ",
    Most_Popular_Categories: "Najpopularnije kategorije",
    Most_Recent_Categories: "Najnovije kategorije",
    Events_Label: "Događaji",
    Forums_Label: "Forumi",
    Issues_Label: "Problemi",
    KnowledgeMgmt_Most_Popular_Articles: "Najpopularniji članci",
    KnowledgeMgmt_Most_Recent_Articles: "Najnoviji članci",
    Knowledge_Base_Label: "Baza znanja",
    Knowledge_Article_Unavailable: "Članak nije dostupan",
    Browse_The_KB: "Pregledajte bazu znanja",
    Popular_Topics: "Popularne teme",
    Related_Categories_DefaultText: "Povezane kategorije",
    Get_Help_DefaultText: "Traženje pomoći",
    Find_Your_Product: "Pronađite svoj proizvod",
    View_More: "Prikaži više",
    Most_Popular: "Najpopularnije",
    Top_Rated_Articles: "Najbolje ocijenjeni članci",
    Case_Deflection_Suggested_Topics: "Predložene teme",
    Sorting_Rating: "Prosječne korisničke ocjene",
    Sorting_Relevance: "Relevantnost",
    Sorting_ViewCount: "Broj prikaza",
    Sorting_Options: "Mogućnosti sortiranja",
    Facet_RecordType: "Vrsta zapisa",
    Facet_DateModified: "Datum promjene",
    Facet_Show_Less: "Prikaži manje",
    Facet_Show_More: "Prikaži više",
    Facet_All: "Sve",
    Facet_Rating: "Ocjena",
    Facet_Products: "Proizvodi",
    Pagination_Current_Page: "Trenutačna stranica {0}",
    Pagination_First_Page: "Prva stranica",
    Pagination_Last_Page: "Zadnja stranica",
    Pagination_Next_Page: "Sljedeća stranica",
    Pagination_Page: "Stranica {0}",
    Pagination_Previous_Page: "Prethodna stranica",
  }),
  "hu-HU": Object.freeze({
    Sign_In: "Bejelentkezés",
    Sign_Out: "Kijelentkezés",
    Profile: "Profil;",
    Search_DefaultText: "Keresés",
    Discover_Contoso: "A Contoso megismerése",
    Toggle_Navigation: "Navigálás be- és kikapcsolása",
    Editable_Cancel_Label: "Mégse",
    Submit_Button_Label_Text: "Küldés",
    Poll_Results_Label: "Eredmények megtekintése",
    Poll_Totals_Label: "Összes szavazat:",
    Poll_Return_Label: "Vissza a szavazáshoz",
    Poll_Archives_Heading: "Archív szavazások",
    Poll_DefaultText: "Szavazás",
    All: "Mind",
    Search_Filter: "Keresési szűrő",
    Search_No_Results_Found: "Nincs találat erre a lekérdezésre: ",
    Search_Results_Format_String: "A lekérdezés eredménye: {0} - {1} / {2}: ",
    Most_Popular_Categories: "Legnépszerűbb kategóriák",
    Most_Recent_Categories: "Legújabb kategóriák",
    Events_Label: "Események",
    Forums_Label: "Fórumok",
    Issues_Label: "Problémák",
    KnowledgeMgmt_Most_Popular_Articles: "Legnépszerűbb cikkek",
    KnowledgeMgmt_Most_Recent_Articles: "Legutóbbi cikkek",
    Knowledge_Base_Label: "Tudásbázis",
    Knowledge_Article_Unavailable: "A cikk nem érhető el",
    Browse_The_KB: "A tudásbázis tallózása",
    Popular_Topics: "Népszerű témakörök",
    Related_Categories_DefaultText: "Kapcsolódó kategóriák",
    Get_Help_DefaultText: "Segítség kérése",
    Find_Your_Product: "Termék megkeresése",
    View_More: "Továbbiak megtekintése",
    Most_Popular: "A legnépszerűbbek",
    Top_Rated_Articles: "A legjobb minősítésű cikkek",
    Case_Deflection_Suggested_Topics: "Javasolt témakörök",
    Sorting_Rating: "Átlagos felhasználói minősítés",
    Sorting_Relevance: "Találati pontosság",
    Sorting_ViewCount: "Megtekintések száma",
    Sorting_Options: "Rendezési lehetőségek",
    Facet_RecordType: "Rekord típusa",
    Facet_DateModified: "Módosítás dátuma",
    Facet_Show_Less: "Kevesebb megjelenítése",
    Facet_Show_More: "Több megjelenítése",
    Facet_All: "Mind",
    Facet_Rating: "Minősítés",
    Facet_Products: "Termékek",
    Pagination_Current_Page: "Aktuális oldal {0}",
    Pagination_First_Page: "Első oldal",
    Pagination_Last_Page: "Utolsó oldal",
    Pagination_Next_Page: "Következő",
    Pagination_Page: "{0}. oldal",
    Pagination_Previous_Page: "Előző oldal",
  }),
  "id-ID": Object.freeze({
    Sign_In: "Masuk",
    Sign_Out: "Keluar",
    Profile: "Profil;",
    Search_DefaultText: "Cari",
    Discover_Contoso: "Temukan Contoso",
    Toggle_Navigation: "Alihkan navigasi",
    Editable_Cancel_Label: "Batal",
    Submit_Button_Label_Text: "Kirim",
    Poll_Results_Label: "Lihat Hasil",
    Poll_Totals_Label: "Total Suara:",
    Poll_Return_Label: "Kembali ke Poling",
    Poll_Archives_Heading: "Arsip Poling",
    Poll_DefaultText: "Poling",
    All: "Semua",
    Search_Filter: "Filter Pencarian",
    Search_No_Results_Found: "Tidak ada hasil yang ditemukan untuk kueri ini: ",
    Search_Results_Format_String: "Hasil {0} - {1} dari {2} untuk kueri: ",
    Most_Popular_Categories: "Kategori Terpopuler",
    Most_Recent_Categories: "Kategori Terbaru",
    Events_Label: "Aktivitas",
    Forums_Label: "Forum",
    Issues_Label: "Masalah",
    KnowledgeMgmt_Most_Popular_Articles: "Artikel Terpopuler",
    KnowledgeMgmt_Most_Recent_Articles: "Artikel Terbaru",
    Knowledge_Base_Label: "Basis Pengetahuan",
    Knowledge_Article_Unavailable: "Artikel Tidak Tersedia",
    Browse_The_KB: "Telusuri KB",
    Popular_Topics: "Topik Populer",
    Related_Categories_DefaultText: "Kategori Terkait",
    Get_Help_DefaultText: "Dapatkan Bantuan",
    Find_Your_Product: "Cari Produk Anda",
    View_More: "Selengkapnya",
    Most_Popular: "Terpopuler",
    Top_Rated_Articles: "Artikel Berperingkat Teratas",
    Case_Deflection_Suggested_Topics: "Topik yang Disarankan",
    Sorting_Rating: "Peringkat Pengguna Rata-Rata",
    Sorting_Relevance: "Relevansi",
    Sorting_ViewCount: "Jumlah Penayangan",
    Sorting_Options: "Opsi pengurutan",
    Facet_RecordType: "Jenis Rekaman",
    Facet_DateModified: "Tanggal modifikasi",
    Facet_Show_Less: "Tampilkan sedikit",
    Facet_Show_More: "Tampilkan lainnya",
    Facet_All: "Semua",
    Facet_Rating: "Peringkat",
    Facet_Products: "Produk",
    Pagination_Current_Page: "Halaman saat ini {0}",
    Pagination_First_Page: "Halaman pertama",
    Pagination_Last_Page: "Halaman terakhir",
    Pagination_Next_Page: "Halaman berikutnya",
    Pagination_Page: "Halaman {0}",
    Pagination_Previous_Page: "Halaman sebelumnya",
  }),
  "it-IT": Object.freeze({
    Sign_In: "Accedi",
    Sign_Out: "Disconnetti",
    Profile: "Profilo;",
    Search_DefaultText: "Cerca",
    Discover_Contoso: "Scopri Contoso",
    Toggle_Navigation: "Attiva/Disattiva navigazione",
    Editable_Cancel_Label: "Annulla",
    Submit_Button_Label_Text: "Invia",
    Poll_Results_Label: "Visualizza risultati",
    Poll_Totals_Label: "Voti totali:",
    Poll_Return_Label: "Torna al sondaggio",
    Poll_Archives_Heading: "Archivi sondaggi",
    Poll_DefaultText: "Sondaggio",
    All: "Tutto",
    Search_Filter: "Filtro ricerca",
    Search_No_Results_Found: "Nessun risultato trovato per questa query: ",
    Search_Results_Format_String: "Risultati {0} - {1} di {2} per la query: ",
    Most_Popular_Categories: "Categorie più consultate",
    Most_Recent_Categories: "Categorie più recenti",
    Events_Label: "Eventi",
    Forums_Label: "Forum",
    Issues_Label: "Problemi",
    KnowledgeMgmt_Most_Popular_Articles: "Articoli più consultati",
    KnowledgeMgmt_Most_Recent_Articles: "Articoli più recenti",
    Knowledge_Base_Label: "Knowledge Base",
    Knowledge_Article_Unavailable: "Articolo non disponibile",
    Browse_The_KB: "Sfoglia la KB",
    Popular_Topics: "Argomenti popolari",
    Related_Categories_DefaultText: "Categorie correlate",
    Get_Help_DefaultText: "Scarica la guida",
    Find_Your_Product: "Trova il tuo prodotto",
    View_More: "Visualizza altro",
    Most_Popular: "Più consultati",
    Top_Rated_Articles: "Articoli migliori",
    Case_Deflection_Suggested_Topics: "Argomenti consigliati",
    Sorting_Rating: "Media valutazioni utente",
    Sorting_Relevance: "Pertinenza",
    Sorting_ViewCount: "Numero visualizzazioni",
    Sorting_Options: "Opzioni di ordinamento",
    Facet_RecordType: "Tipo di record",
    Facet_DateModified: "Data ultima modifica",
    Facet_Show_Less: "Mostra meno",
    Facet_Show_More: "Mostra altro",
    Facet_All: "Tutto",
    Facet_Rating: "Valutazione",
    Facet_Products: "Prodotti",
    Pagination_Current_Page: "Pagina corrente {0}",
    Pagination_First_Page: "Prima pagina",
    Pagination_Last_Page: "Ultima pagina",
    Pagination_Next_Page: "Pagina successiva",
    Pagination_Page: "Pagina {0}",
    Pagination_Previous_Page: "Pagina precedente",
  }),
  "ja-JP": Object.freeze({
    Sign_In: "サインイン",
    Sign_Out: "サインアウト",
    Profile: "プロファイル;",
    Search_DefaultText: "検索",
    Discover_Contoso: "Contoso の検出",
    Toggle_Navigation: "ナビゲーションの切り替え",
    Editable_Cancel_Label: "キャンセル",
    Submit_Button_Label_Text: "送信",
    Poll_Results_Label: "結果の表示",
    Poll_Totals_Label: "合計票数:",
    Poll_Return_Label: "アンケートに戻る",
    Poll_Archives_Heading: "アンケートのアーカイブ",
    Poll_DefaultText: "アンケート",
    All: "すべて",
    Search_Filter: "検索フィルター",
    Search_No_Results_Found: "このクエリに該当する結果が見つかりませんでした: ",
    Search_Results_Format_String: "クエリの結果 {2} 件中 {0} - {1}: ",
    Most_Popular_Categories: "最も人気のあるカテゴリ",
    Most_Recent_Categories: "最新のカテゴリ",
    Events_Label: "イベント",
    Forums_Label: "フォーラム",
    Issues_Label: "問題",
    KnowledgeMgmt_Most_Popular_Articles: "最も人気のある記事",
    KnowledgeMgmt_Most_Recent_Articles: "最新の記事",
    Knowledge_Base_Label: "サポート情報",
    Knowledge_Article_Unavailable: "記事は使用できません",
    Browse_The_KB: "サポート情報の参照",
    Popular_Topics: "よく読まれているトピック",
    Related_Categories_DefaultText: "関連カテゴリ",
    Get_Help_DefaultText: "ヘルプの参照",
    Find_Your_Product: "製品の検索",
    View_More: "さらに表示",
    Most_Popular: "大人気",
    Top_Rated_Articles: "評価の高い記事",
    Case_Deflection_Suggested_Topics: "推奨トピック",
    Sorting_Rating: "平均ユーザー評価",
    Sorting_Relevance: "関連性",
    Sorting_ViewCount: "表示回数",
    Sorting_Options: "並べ替えのオプション",
    Facet_RecordType: "レコードの種類",
    Facet_DateModified: "修正日",
    Facet_Show_Less: "簡易表示",
    Facet_Show_More: "詳細表示",
    Facet_All: "すべて",
    Facet_Rating: "評価",
    Facet_Products: "製品",
    Pagination_Current_Page: "現在のページ {0}",
    Pagination_First_Page: "最初のページ",
    Pagination_Last_Page: "最後のページ",
    Pagination_Next_Page: "次のページ",
    Pagination_Page: "{0} ページ",
    Pagination_Previous_Page: "前のページ",
  }),
  "kk-KZ": Object.freeze({
    Sign_In: "Кіру",
    Sign_Out: "Шығу",
    Profile: "Профиль;",
    Search_DefaultText: "Іздеу",
    Discover_Contoso: "Contoso табу",
    Toggle_Navigation: "Навигацияны қосу",
    Editable_Cancel_Label: "Болдырмау",
    Submit_Button_Label_Text: "Жіберу",
    Poll_Results_Label: "Нәтижелерді көру",
    Poll_Totals_Label: "Барлық дауыстар:",
    Poll_Return_Label: "Сұрауға оралу",
    Poll_Archives_Heading: "Сұраулар мұрағаты",
    Poll_DefaultText: "Сұрау",
    All: "Барлығы",
    Search_Filter: "Сүзгіні іздеу",
    Search_No_Results_Found: "Осы сұрау бойынша нәтижелер табылмады: ",
    Search_Results_Format_String: "{2} ішінен {0} - {1} сұрауынан іздеу: ",
    Most_Popular_Categories: "Ең танымал санаттар",
    Most_Recent_Categories: "Ең соңғы санаттар",
    Events_Label: "Оқиғалар",
    Forums_Label: "Форумдар",
    Issues_Label: "Мәселелер",
    KnowledgeMgmt_Most_Popular_Articles: "Ең танымал мақалалар",
    KnowledgeMgmt_Most_Recent_Articles: "Ең соңғы мақалалар",
    Knowledge_Base_Label: "Білім қоры",
    Knowledge_Article_Unavailable: "Мақала қолжетімді емес",
    Browse_The_KB: "Білім қорын шолу",
    Popular_Topics: "Танымал мақалалар",
    Related_Categories_DefaultText: "Қатысты санаттар",
    Get_Help_DefaultText: "Анықтама алу",
    Find_Your_Product: "Порталды іздеу",
    View_More: "Көбірек көру",
    Most_Popular: "Ең танымал",
    Top_Rated_Articles: "Ең жоғары баға берілген мақалалар",
    Case_Deflection_Suggested_Topics: "Ұсынылған тақырыптар",
    Sorting_Rating: "Орташа пайдаланушы бағасы",
    Sorting_Relevance: "Маңыздылық",
    Sorting_ViewCount: "Көрініс саны",
    Sorting_Options: "Сұрыптау параметрлері",
    Facet_RecordType: "Жазба түрі",
    Facet_DateModified: "Өзгертілген күні",
    Facet_Show_Less: "Азырақ",
    Facet_Show_More: "Көбірек",
    Facet_All: "Барлығы",
    Facet_Rating: "Бағалау",
    Facet_Products: "Өнімдер",
    Pagination_Current_Page: "Ағымдағы бет {0}",
    Pagination_First_Page: "Бірінші бет",
    Pagination_Last_Page: "Соңғы бет",
    Pagination_Next_Page: "Келесі бет",
    Pagination_Page: "{0}-бет",
    Pagination_Previous_Page: "Алдыңғы бет",
  }),
  "ko-KR": Object.freeze({
    Sign_In: "로그인",
    Sign_Out: "로그아웃",
    Profile: "프로필;",
    Search_DefaultText: "검색",
    Discover_Contoso: "Contoso 발견",
    Toggle_Navigation: "탐색 전환",
    Editable_Cancel_Label: "취소",
    Submit_Button_Label_Text: "제출",
    Poll_Results_Label: "결과 보기",
    Poll_Totals_Label: "총 투표:",
    Poll_Return_Label: "설문 조사로 돌아가기",
    Poll_Archives_Heading: "지난 설문 조사",
    Poll_DefaultText: "설문 조사",
    All: "모두",
    Search_Filter: "검색 필터",
    Search_No_Results_Found: "이 쿼리에 대한 결과 없음: ",
    Search_Results_Format_String: "결과 {0} - 쿼리에 대해 {2} 중 {1}: ",
    Most_Popular_Categories: "최고 인기 범주",
    Most_Recent_Categories: "가장 최근 범주",
    Events_Label: "이벤트",
    Forums_Label: "포럼",
    Issues_Label: "문제",
    KnowledgeMgmt_Most_Popular_Articles: "최고 인기 문서",
    KnowledgeMgmt_Most_Recent_Articles: "최신 문서",
    Knowledge_Base_Label: "참조 자료",
    Knowledge_Article_Unavailable: "문서를 사용할 수 없음",
    Browse_The_KB: "참조 자료 찾아보기",
    Popular_Topics: "인기 있는 주제",
    Related_Categories_DefaultText: "관련 범주",
    Get_Help_DefaultText: "지원 받기",
    Find_Your_Product: "제품 찾기",
    View_More: "추가 보기",
    Most_Popular: "인기 자료",
    Top_Rated_Articles: "최고 평점 문서",
    Case_Deflection_Suggested_Topics: "제안 항목",
    Sorting_Rating: "평균 사용자 등급",
    Sorting_Relevance: "관련성",
    Sorting_ViewCount: "보기 개수",
    Sorting_Options: "정렬 옵션",
    Facet_RecordType: "레코드 종류",
    Facet_DateModified: "수정한 날짜",
    Facet_Show_Less: "적게 표시",
    Facet_Show_More: "많이 표시",
    Facet_All: "모두",
    Facet_Rating: "등급",
    Facet_Products: "제품",
    Pagination_Current_Page: "현재 페이지 {0}",
    Pagination_First_Page: "첫 페이지",
    Pagination_Last_Page: "마지막 페이지",
    Pagination_Next_Page: "다음 페이지",
    Pagination_Page: "{0}페이지",
    Pagination_Previous_Page: "이전 페이지",
  }),
  "lt-LT": Object.freeze({
    Sign_In: "Prisijungti",
    Sign_Out: "Atsijungti",
    Profile: "Profilis;",
    Search_DefaultText: "Ieškoti",
    Discover_Contoso: "Atraskite „Contoso“",
    Toggle_Navigation: "Perjungti naršymą",
    Editable_Cancel_Label: "Atšaukti",
    Submit_Button_Label_Text: "Pateikti",
    Poll_Results_Label: "Rodyti rezultatus",
    Poll_Totals_Label: "Bendras balsų skaičius:",
    Poll_Return_Label: "Grįžti į apklausą",
    Poll_Archives_Heading: "Apklausų archyvai",
    Poll_DefaultText: "Apklausa",
    All: "Visi",
    Search_Filter: "Ieškos filtras",
    Search_No_Results_Found: "Pagal šią užklausą jokių rezultatų nerasta:",
    Search_Results_Format_String: "{0}–{1} rezult. iš {2} pagal užklausą: ",
    Most_Popular_Categories: "Populiariausios kategorijos",
    Most_Recent_Categories: "Naujausios kategorijos",
    Events_Label: "Įvykiai",
    Forums_Label: "Forumai",
    Issues_Label: "Problemos",
    KnowledgeMgmt_Most_Popular_Articles: "Populiariausi straipsniai",
    KnowledgeMgmt_Most_Recent_Articles: "Naujausi straipsniai",
    Knowledge_Base_Label: "Žinių bazė",
    Knowledge_Article_Unavailable: "Straipsnis nepasiekiamas",
    Browse_The_KB: "Naršyti žinių bazę",
    Popular_Topics: "Populiarios temos",
    Related_Categories_DefaultText: "Susijusios kategorijos",
    Get_Help_DefaultText: "Gauti pagalbos",
    Find_Your_Product: "Raskite produktą",
    View_More: "Rodyti daugiau",
    Most_Popular: "Populiariausi",
    Top_Rated_Articles: "Geriausiai įvertinti straipsniai",
    Case_Deflection_Suggested_Topics: "Siūlomos temos",
    Sorting_Rating: "Vidutiniai vartotojų įverčiai",
    Sorting_Relevance: "Atitiktis",
    Sorting_ViewCount: "Peržiūrų skaičius",
    Sorting_Options: "Rūšiavimo parinktys",
    Facet_RecordType: "Įrašo tipas",
    Facet_DateModified: "Modifikavimo data",
    Facet_Show_Less: "Rodyti mažiau",
    Facet_Show_More: "Rodyti daugiau",
    Facet_All: "Visi",
    Facet_Rating: "Įvertinimas",
    Facet_Products: "Produktai",
    Pagination_Current_Page: "Dabartinis puslapis {0}",
    Pagination_First_Page: "Pirmasis puslapis",
    Pagination_Last_Page: "Paskutinis puslapis",
    Pagination_Next_Page: "Kitas puslapis",
    Pagination_Page: "{0} puslapis",
    Pagination_Previous_Page: "Ankstesnis puslapis",
  }),
  "lv-LV": Object.freeze({
    Sign_In: "Pierakstīties",
    Sign_Out: "Izrakstīties",
    Profile: "Profils;",
    Search_DefaultText: "Meklēt",
    Discover_Contoso: "Atklāt Contoso",
    Toggle_Navigation: "Pārslēgt navigāciju",
    Editable_Cancel_Label: "Atcelt",
    Submit_Button_Label_Text: "Iesniegt",
    Poll_Results_Label: "Skatīt rezultātus",
    Poll_Totals_Label: "Kopējais balstu skaits:",
    Poll_Return_Label: "Atgriezties aptaujā",
    Poll_Archives_Heading: "Aptauju arhīvi",
    Poll_DefaultText: "Aptauja",
    All: "Visi",
    Search_Filter: "Meklēšanas rezultātu filtrs",
    Search_No_Results_Found: "Šim vaicājumam netika atrasti nekādi rezultāti: ",
    Search_Results_Format_String: "Vaicājuma rezultāti {0} - {1} no {2}: ",
    Most_Popular_Categories: "Populārākās kategorijas",
    Most_Recent_Categories: "Jaunākās kategorijas",
    Events_Label: "Notikumi",
    Forums_Label: "Forumi",
    Issues_Label: "Problēmas",
    KnowledgeMgmt_Most_Popular_Articles: "Populārākie raksti",
    KnowledgeMgmt_Most_Recent_Articles: "Jaunākie raksti",
    Knowledge_Base_Label: "Zināšanu bāze",
    Knowledge_Article_Unavailable: "Raksts nav pieejams",
    Browse_The_KB: "Pārlūkot zināšanu bāzi",
    Popular_Topics: "Populāras tēmas",
    Related_Categories_DefaultText: "Saistītās kategorijas",
    Get_Help_DefaultText: "Palīdzības saņemšana",
    Find_Your_Product: "Atrodiet produktu",
    View_More: "Skatīt vairāk",
    Most_Popular: "Populārākie",
    Top_Rated_Articles: "Visaugstāk novērtētie raksti",
    Case_Deflection_Suggested_Topics: "Ieteicamās tēmas",
    Sorting_Rating: "Vidējie lietotāju vērtējumi",
    Sorting_Relevance: "Atbilstība",
    Sorting_ViewCount: "Skatījumu skaits",
    Sorting_Options: "Kārtošanas opcijas",
    Facet_RecordType: "Ieraksta tips",
    Facet_DateModified: "Modificēts:",
    Facet_Show_Less: "Rādīt mazāk",
    Facet_Show_More: "Rādīt vairāk",
    Facet_All: "Visi",
    Facet_Rating: "Vērtējums",
    Facet_Products: "Produkti",
    Pagination_Current_Page: "Pašreizējā lapa {0}",
    Pagination_First_Page: "Pirmā lapa",
    Pagination_Last_Page: "Pēdējā lapa",
    Pagination_Next_Page: "Nākamā lapa",
    Pagination_Page: "{0}. lapa",
    Pagination_Previous_Page: "Iepriekšējā lapa",
  }),
  "ms-MY": Object.freeze({
    Sign_In: "Daftar Masuk",
    Sign_Out: "Daftar Keluar",
    Profile: "Profil;",
    Search_DefaultText: "Cari",
    Discover_Contoso: "Temui Contoso",
    Toggle_Navigation: "Navigasi Togol",
    Editable_Cancel_Label: "Batal",
    Submit_Button_Label_Text: "Serah",
    Poll_Results_Label: "Lihat Hasil",
    Poll_Totals_Label: "Jumlah Undi:",
    Poll_Return_Label: "Kembali ke Pungutan Suara",
    Poll_Archives_Heading: "Arkib Pungutan Suara",
    Poll_DefaultText: "Tinjauan",
    All: "Semua",
    Search_Filter: "Penapis Carian",
    Search_No_Results_Found: "Tiada hasil yang ditemui untuk pertanyaan ini:",
    Search_Results_Format_String: "Hasil {0} - {1} daripada {2} untuk pertanyaan:",
    Most_Popular_Categories: "Kategori Paling Popular",
    Most_Recent_Categories: "Kategori Terkini",
    Events_Label: "Peristiwa",
    Forums_Label: "Forum",
    Issues_Label: "Isu-isu",
    KnowledgeMgmt_Most_Popular_Articles: "Artikel Paling Popular",
    KnowledgeMgmt_Most_Recent_Articles: "Artikel Terkini",
    Knowledge_Base_Label: "Pangkalan Pengetahuan",
    Knowledge_Article_Unavailable: "Artikel Tidak Tersedia",
    Browse_The_KB: "Layari KB",
    Popular_Topics: "Topik Popular",
    Related_Categories_DefaultText: "Kategori Berkaitan",
    Get_Help_DefaultText: "Dapatkan Bantuan",
    Find_Your_Product: "Cari Produk anda",
    View_More: "Lihat Lagi",
    Most_Popular: "Paling Popular",
    Top_Rated_Articles: "Artikel Dinilai Terbaik",
    Case_Deflection_Suggested_Topics: "Topik Dicadangkan",
    Sorting_Rating: "Purata Pengadaran Pengguna",
    Sorting_Relevance: "Keterkaitan",
    Sorting_ViewCount: "Pandangan Kiraan",
    Sorting_Options: "Pilihan penyisihan",
    Facet_RecordType: "Jenis Rekod",
    Facet_DateModified: "Tarikh diubah suai",
    Facet_Show_Less: "Tunjukkan kurang",
    Facet_Show_More: "Tunjukkan lagi",
    Facet_All: "Semua",
    Facet_Rating: "Penilaian",
    Facet_Products: "Produk",
    Pagination_Current_Page: "Halaman semasa {0}",
    Pagination_First_Page: "Halaman pertama",
    Pagination_Last_Page: "Halaman terakhir",
    Pagination_Next_Page: "Halaman seterusnya",
    Pagination_Page: "Halaman {0}",
    Pagination_Previous_Page: "Halaman sebelumnya",
  }),
  "nb-NO": Object.freeze({
    Sign_In: "Logg på",
    Sign_Out: "Logg av",
    Profile: "Profil;",
    Search_DefaultText: "Søk",
    Discover_Contoso: "Oppdag Contoso",
    Toggle_Navigation: "Aktiver/deaktiver navigering",
    Editable_Cancel_Label: "Avbryt",
    Submit_Button_Label_Text: "Send",
    Poll_Results_Label: "Vis resultater",
    Poll_Totals_Label: "Totalt antall stemmer:",
    Poll_Return_Label: "Gå tilbake til avspørring",
    Poll_Archives_Heading: "Avspørringsarkiv",
    Poll_DefaultText: "Avspørring",
    All: "Alle",
    Search_Filter: "Søkefilter",
    Search_No_Results_Found: "Fant ingen resultater for denne spørringen: ",
    Search_Results_Format_String: "Resultater {0} – {1} av {2} for spørring: ",
    Most_Popular_Categories: "Mest populære kategorier",
    Most_Recent_Categories: "De nyeste kategoriene",
    Events_Label: "Hendelser",
    Forums_Label: "Fora",
    Issues_Label: "Problemer",
    KnowledgeMgmt_Most_Popular_Articles: "Mest populære artikler",
    KnowledgeMgmt_Most_Recent_Articles: "De nyeste artiklene",
    Knowledge_Base_Label: "Kunnskapsbase",
    Knowledge_Article_Unavailable: "Utilgjengelig artikkel",
    Browse_The_KB: "Bla gjennom kunnskapsbasen",
    Popular_Topics: "Populære emner",
    Related_Categories_DefaultText: "Relaterte kategorier",
    Get_Help_DefaultText: "Få hjelp",
    Find_Your_Product: "Finn produktet",
    View_More: "Vis mer",
    Most_Popular: "Mest populær",
    Top_Rated_Articles: "Høyest vurderte artikler",
    Case_Deflection_Suggested_Topics: "Foreslåtte emner",
    Sorting_Rating: "Gjennomsnittlige brukervurderinger",
    Sorting_Relevance: "Relevans",
    Sorting_ViewCount: "Antall visninger",
    Sorting_Options: "Sorteringsalternativer",
    Facet_RecordType: "Oppføringstype",
    Facet_DateModified: "Endret dato",
    Facet_Show_Less: "Vis mindre",
    Facet_Show_More: "Vis mer",
    Facet_All: "Alle",
    Facet_Rating: "Vurdering",
    Facet_Products: "Produkter",
    Pagination_Current_Page: "Gjeldende side {0}",
    Pagination_First_Page: "Første side",
    Pagination_Last_Page: "Siste side",
    Pagination_Next_Page: "Neste side",
    Pagination_Page: "Side {0}",
    Pagination_Previous_Page: "Forrige side",
  }),
  "nl-NL": Object.freeze({
    Sign_In: "Aanmelden",
    Sign_Out: "Afmelden",
    Profile: "Profiel;",
    Search_DefaultText: "Zoeken",
    Discover_Contoso: "Ontdek Contoso",
    Toggle_Navigation: "Navigatie omschakelen",
    Editable_Cancel_Label: "Annuleren",
    Submit_Button_Label_Text: "Indienen",
    Poll_Results_Label: "Resultaten weergeven",
    Poll_Totals_Label: "Totale stemmen:",
    Poll_Return_Label: "Terugkeren naar peiling",
    Poll_Archives_Heading: "Peilingarchieven",
    Poll_DefaultText: "Peiling",
    All: "Alle",
    Search_Filter: "Zoekfilter",
    Search_No_Results_Found: "Er zijn geen resultaten gevonden voor deze query: ",
    Search_Results_Format_String: "Resultaten {0} - {1} of {2} voor query: ",
    Most_Popular_Categories: "Populairste categorieën",
    Most_Recent_Categories: "Meest recente categorieën",
    Events_Label: "Gebeurtenissen",
    Forums_Label: "Forums",
    Issues_Label: "Problemen",
    KnowledgeMgmt_Most_Popular_Articles: "Populairste artikelen",
    KnowledgeMgmt_Most_Recent_Articles: "Meest recente artikelen",
    Knowledge_Base_Label: "Knowledge Base",
    Knowledge_Article_Unavailable: "Artikel niet beschikbaar",
    Browse_The_KB: "Bladeren in de KB",
    Popular_Topics: "Populaire onderwerpen",
    Related_Categories_DefaultText: "Gerelateerde categorieën",
    Get_Help_DefaultText: "Help opvragen",
    Find_Your_Product: "Uw product zoeken",
    View_More: "Meer weergeven",
    Most_Popular: "Meest populair",
    Top_Rated_Articles: "Beste artikelen",
    Case_Deflection_Suggested_Topics: "Voorgestelde onderwerpen",
    Sorting_Rating: "Gemiddelde beoordelingen gebruiker",
    Sorting_Relevance: "Relevantie",
    Sorting_ViewCount: "Aantal keren bekeken",
    Sorting_Options: "Sorteeropties",
    Facet_RecordType: "Recordtype",
    Facet_DateModified: "Gewijzigd op",
    Facet_Show_Less: "Minder weergeven",
    Facet_Show_More: "Meer weergeven",
    Facet_All: "Alle",
    Facet_Rating: "Beoordeling",
    Facet_Products: "Producten",
    Pagination_Current_Page: "Huidige pagina {0}",
    Pagination_First_Page: "Eerste pagina",
    Pagination_Last_Page: "Laatste pagina",
    Pagination_Next_Page: "Volgende pagina",
    Pagination_Page: "Pagina {0}",
    Pagination_Previous_Page: "Vorige pagina",
  }),
  "pl-PL": Object.freeze({
    Sign_In: "Zaloguj",
    Sign_Out: "Wyloguj",
    Profile: "Profil;",
    Search_DefaultText: "Wyszukaj",
    Discover_Contoso: "Poznaj firmę Contoso",
    Toggle_Navigation: "Przełącz nawigację",
    Editable_Cancel_Label: "Anuluj",
    Submit_Button_Label_Text: "Prześlij",
    Poll_Results_Label: "Wyświetl wyniki",
    Poll_Totals_Label: "Łączna liczba głosów:",
    Poll_Return_Label: "Powrót do ankiety",
    Poll_Archives_Heading: "Archiwa ankiet",
    Poll_DefaultText: "Ankieta",
    All: "Wszystko",
    Search_Filter: "Filtr wyszukiwania",
    Search_No_Results_Found: "Nie znaleziono wyników dla tego zapytania: ",
    Search_Results_Format_String: "Wyniki {0} — {1} z {2} dla zapytania: ",
    Most_Popular_Categories: "Najpopularniejsze kategorie",
    Most_Recent_Categories: "Najnowsze kategorie",
    Events_Label: "Wydarzenia",
    Forums_Label: "Fora",
    Issues_Label: "Problemy",
    KnowledgeMgmt_Most_Popular_Articles: "Najpopularniejsze artykuły",
    KnowledgeMgmt_Most_Recent_Articles: "Najnowsze artykuły",
    Knowledge_Base_Label: "Baza wiedzy",
    Knowledge_Article_Unavailable: "Artykuł niedostępny",
    Browse_The_KB: "Przeglądaj bazę wiedzy",
    Popular_Topics: "Popularne tematy",
    Related_Categories_DefaultText: "Powiązane kategorie",
    Get_Help_DefaultText: "Uzyskaj pomoc",
    Find_Your_Product: "Znajdź produkt",
    View_More: "Wyświetl więcej",
    Most_Popular: "Najpopularniejsze",
    Top_Rated_Articles: "Najwyżej oceniane artykuły",
    Case_Deflection_Suggested_Topics: "Sugerowane tematy",
    Sorting_Rating: "Średnie oceny użytkowników",
    Sorting_Relevance: "Stopień zgodności",
    Sorting_ViewCount: "Liczba wyświetleń",
    Sorting_Options: "Opcje sortowania",
    Facet_RecordType: "Typ rekordu",
    Facet_DateModified: "Data modyfikacji",
    Facet_Show_Less: "Pokaż mniej",
    Facet_Show_More: "Pokaż więcej",
    Facet_All: "Wszystko",
    Facet_Rating: "Ocena",
    Facet_Products: "Produkty",
    Pagination_Current_Page: "Bieżąca strona {0}",
    Pagination_First_Page: "Pierwsza strona",
    Pagination_Last_Page: "Ostatnia strona",
    Pagination_Next_Page: "Następna strona",
    Pagination_Page: "Strona {0}",
    Pagination_Previous_Page: "Poprzednia strona",
  }),
  "pt-BR": Object.freeze({
    Sign_In: "Entrar",
    Sign_Out: "Sair",
    Profile: "Perfil;",
    Search_DefaultText: "Pesquisar",
    Discover_Contoso: "Descobrir Contoso",
    Toggle_Navigation: "Alternar navegação",
    Editable_Cancel_Label: "Cancelar",
    Submit_Button_Label_Text: "Enviar",
    Poll_Results_Label: "Exibir Resultados",
    Poll_Totals_Label: "Total de Votos:",
    Poll_Return_Label: "Retornar à Pesquisa de Opinião",
    Poll_Archives_Heading: "Arquivos de Pesquisa de Opinião",
    Poll_DefaultText: "Páginas da Web Raiz",
    All: "Tudo",
    Search_Filter: "Filtro de Pesquisa",
    Search_No_Results_Found: "Nenhum resultado foi encontrado para esta consulta: ",
    Search_Results_Format_String: "Resultados {0} - {1} de {2} para a consulta: ",
    Most_Popular_Categories: "As Categorias Mais Populares",
    Most_Recent_Categories: "As Categorias Mais Recentes",
    Events_Label: "Eventos",
    Forums_Label: "Fóruns",
    Issues_Label: "Problemas",
    KnowledgeMgmt_Most_Popular_Articles: "Os Artigos Mais Populares",
    KnowledgeMgmt_Most_Recent_Articles: "Os Artigos Mais Recentes",
    Knowledge_Base_Label: "Base de Dados de Conhecimento",
    Knowledge_Article_Unavailable: "Artigo Indisponível",
    Browse_The_KB: "Procurar na Base de Dados de Conhecimento",
    Popular_Topics: "Tópicos Populares",
    Related_Categories_DefaultText: "Categorias Relacionadas",
    Get_Help_DefaultText: "Obter Ajuda",
    Find_Your_Product: "Localize seu Produto",
    View_More: "Exibir Mais",
    Most_Popular: "Mais Populares",
    Top_Rated_Articles: "Artigos Mais Avaliados",
    Case_Deflection_Suggested_Topics: "Tópicos Sugeridos",
    Sorting_Rating: "Média de Classificações do Usuário",
    Sorting_Relevance: "Relevância",
    Sorting_ViewCount: "Exibir Contagem",
    Sorting_Options: "Opções de classificação",
    Facet_RecordType: "Tipo de Registro",
    Facet_DateModified: "Data da modificação",
    Facet_Show_Less: "Mostrar menos",
    Facet_Show_More: "Mostrar mais",
    Facet_All: "Tudo",
    Facet_Rating: "Classificação",
    Facet_Products: "Produtos",
    Pagination_Current_Page: "Página atual {0}",
    Pagination_First_Page: "Primeira página",
    Pagination_Last_Page: "Última página",
    Pagination_Next_Page: "Próxima página",
    Pagination_Page: "Página {0}",
    Pagination_Previous_Page: "Página anterior",
  }),
  "pt-PT": Object.freeze({
    Sign_In: "Iniciar Sessão",
    Sign_Out: "Terminar Sessão",
    Profile: "Perfil;",
    Search_DefaultText: "Procurar",
    Discover_Contoso: "Detetar Contoso",
    Toggle_Navigation: "Ativar/desativar navegação",
    Editable_Cancel_Label: "Cancelar",
    Submit_Button_Label_Text: "Submeter",
    Poll_Results_Label: "Ver Resultados",
    Poll_Totals_Label: "Total de Votos:",
    Poll_Return_Label: "Regressar à Sondagem",
    Poll_Archives_Heading: "Arquivos de Sondagens",
    Poll_DefaultText: "Sondagem",
    All: "Tudo",
    Search_Filter: "Filtro de Pesquisa",
    Search_No_Results_Found: "Não foram encontrados resultados para esta consulta: ",
    Search_Results_Format_String: "Resultados {0} - {1} de {2} para consulta: ",
    Most_Popular_Categories: "Categorias Mais Populares",
    Most_Recent_Categories: "Categorias Mais Recentes",
    Events_Label: "Eventos",
    Forums_Label: "Fóruns",
    Issues_Label: "Problemas",
    KnowledgeMgmt_Most_Popular_Articles: "Artigos Mais Populares",
    KnowledgeMgmt_Most_Recent_Articles: "Artigos Mais Recentes",
    Knowledge_Base_Label: "Base de Dados de Conhecimento",
    Knowledge_Article_Unavailable: "Artigo Indisponível",
    Browse_The_KB: "Procurar na BDC",
    Popular_Topics: "Tópicos Populares",
    Related_Categories_DefaultText: "Categorias Relacionadas",
    Get_Help_DefaultText: "Obter Ajuda",
    Find_Your_Product: "Localizar o seu Produto",
    View_More: "Ver Mais",
    Most_Popular: "Mais Populares",
    Top_Rated_Articles: "Artigos Melhor Classificados",
    Case_Deflection_Suggested_Topics: "Tópicos Sugeridos",
    Sorting_Rating: "Classificações Médias de Utilizador",
    Sorting_Relevance: "Relevância",
    Sorting_ViewCount: "Contagem de Visualizações",
    Sorting_Options: "Opções de ordenação",
    Facet_RecordType: "Tipo de Registo",
    Facet_DateModified: "Data de modificação",
    Facet_Show_Less: "Mostrar menos",
    Facet_Show_More: "Mostrar mais",
    Facet_All: "Tudo",
    Facet_Rating: "Classificação",
    Facet_Products: "Produtos",
    Pagination_Current_Page: "Página atual {0}",
    Pagination_First_Page: "Primeira página",
    Pagination_Last_Page: "Última página",
    Pagination_Next_Page: "Página Seguinte",
    Pagination_Page: "Página {0}",
    Pagination_Previous_Page: "Página Anterior",
  }),
  "ro-RO": Object.freeze({
    Sign_In: "Conectare",
    Sign_Out: "Deconectare",
    Profile: "Profil;",
    Search_DefaultText: "Căutare",
    Discover_Contoso: "Descoperiți Contoso",
    Toggle_Navigation: "Comutați navigarea",
    Editable_Cancel_Label: "Anulare",
    Submit_Button_Label_Text: "Remitere",
    Poll_Results_Label: "Vizualizați rezultatele",
    Poll_Totals_Label: "Total voturi:",
    Poll_Return_Label: "Revenire la interogare",
    Poll_Archives_Heading: "Arhive de interogare",
    Poll_DefaultText: "Sondaj",
    All: "Toate",
    Search_Filter: "Filtru de căutare",
    Search_No_Results_Found: "Nu s-au găsit rezultate pentru această interogare: ",
    Search_Results_Format_String: "Rezultate {0} - {1} din {2} pentru interogare: ",
    Most_Popular_Categories: "Cele mai populare categorii",
    Most_Recent_Categories: "Cele mai recente categorii",
    Events_Label: "Evenimente",
    Forums_Label: "Forumuri",
    Issues_Label: "Probleme",
    KnowledgeMgmt_Most_Popular_Articles: "Cele mai populare articole",
    KnowledgeMgmt_Most_Recent_Articles: "Cele mai recente articole",
    Knowledge_Base_Label: "Bază de cunoștințe",
    Knowledge_Article_Unavailable: "Articol indisponibil",
    Browse_The_KB: "Navigați prin Baza de cunoștințe",
    Popular_Topics: "Subiecte populare",
    Related_Categories_DefaultText: "Categorii corelate",
    Get_Help_DefaultText: "Obțineți ajutor",
    Find_Your_Product: "Găsiți-vă produsul",
    View_More: "Vedeți mai multe",
    Most_Popular: "Cele mai populare",
    Top_Rated_Articles: "Cele mai importante articole",
    Case_Deflection_Suggested_Topics: "Subiecte sugerate",
    Sorting_Rating: "Evaluare medie utilizatori",
    Sorting_Relevance: "Relevanță",
    Sorting_ViewCount: "Număr vizualizări",
    Sorting_Options: "Opțiuni de sortare",
    Facet_RecordType: "Tip înregistrare",
    Facet_DateModified: "Data modificării",
    Facet_Show_Less: "Afișați mai puțin",
    Facet_Show_More: "Afișați mai mult",
    Facet_All: "Toate",
    Facet_Rating: "Cotare",
    Facet_Products: "Produse",
    Pagination_Current_Page: "Pagina curentă {0}",
    Pagination_First_Page: "Prima pagină",
    Pagination_Last_Page: "Ultima pagină",
    Pagination_Next_Page: "Pagina următoare",
    Pagination_Page: "Pagina {0}",
    Pagination_Previous_Page: "Pagina precedentă",
  }),
  "ru-RU": Object.freeze({
    Sign_In: "Вход",
    Sign_Out: "Выход",
    Profile: "Профиль;",
    Search_DefaultText: "Поиск",
    Discover_Contoso: "Обнаружить Contoso",
    Toggle_Navigation: "Переключить навигацию",
    Editable_Cancel_Label: "Отмена",
    Submit_Button_Label_Text: "Отправить",
    Poll_Results_Label: "Показать результаты",
    Poll_Totals_Label: "Всего голосов:",
    Poll_Return_Label: "Вернуться к опросу",
    Poll_Archives_Heading: "Архивы опросов",
    Poll_DefaultText: "Опрос",
    All: "Все",
    Search_Filter: "Фильтр поиска",
    Search_No_Results_Found: "Не найдены результаты, удовлетворяющие этому запросу: ",
    Search_Results_Format_String: "Результаты {0}–{1} из {2} для запроса:",
    Most_Popular_Categories: "Самые популярные категории",
    Most_Recent_Categories: "Самые новые категории",
    Events_Label: "События",
    Forums_Label: "Форумы",
    Issues_Label: "Проблемы",
    KnowledgeMgmt_Most_Popular_Articles: "Самые популярные статьи",
    KnowledgeMgmt_Most_Recent_Articles: "Самые новые статьи",
    Knowledge_Base_Label: "База знаний",
    Knowledge_Article_Unavailable: "Статья недоступна",
    Browse_The_KB: "Просмотр базы знаний",
    Popular_Topics: "Популярные темы",
    Related_Categories_DefaultText: "Связанные категории",
    Get_Help_DefaultText: "Получить справку",
    Find_Your_Product: "Поиск продукта",
    View_More: "Просмотреть больше",
    Most_Popular: "Самые популярные",
    Top_Rated_Articles: "Самые популярные статьи",
    Case_Deflection_Suggested_Topics: "Предлагаемые темы",
    Sorting_Rating: "Средний рейтинг пользователей",
    Sorting_Relevance: "Релевантность",
    Sorting_ViewCount: "Число просмотров",
    Sorting_Options: "Параметры сортировки",
    Facet_RecordType: "Тип записей",
    Facet_DateModified: "Дата изменения",
    Facet_Show_Less: "Показать меньше",
    Facet_Show_More: "Показать больше",
    Facet_All: "Все",
    Facet_Rating: "Оценка",
    Facet_Products: "Продукты",
    Pagination_Current_Page: "Текущая страница {0}",
    Pagination_First_Page: "Первая страница",
    Pagination_Last_Page: "Последняя страница",
    Pagination_Next_Page: "Следующая страница",
    Pagination_Page: "Стр. {0}",
    Pagination_Previous_Page: "Предыдущая страница",
  }),
  "sk-SK": Object.freeze({
    Sign_In: "Prihlásiť sa",
    Sign_Out: "Odhlásiť sa",
    Profile: "Profil,",
    Search_DefaultText: "Hľadať",
    Discover_Contoso: "Spoznať spoločnosť Contoso",
    Toggle_Navigation: "Prepnúť navigáciu",
    Editable_Cancel_Label: "Zrušiť",
    Submit_Button_Label_Text: "Odoslať",
    Poll_Results_Label: "Zobraziť výsledky",
    Poll_Totals_Label: "Celkový počet hlasov:",
    Poll_Return_Label: "Vrátiť sa k hlasovaniu",
    Poll_Archives_Heading: "Archívy hlasovania",
    Poll_DefaultText: "Hlasovanie",
    All: "Všetko",
    Search_Filter: "Filter vyhľadávania",
    Search_No_Results_Found: "Pre tento dotaz sa nenašli žiadne výsledky: ",
    Search_Results_Format_String: "Výsledky {0} – {1} z {2} pre dotaz: ",
    Most_Popular_Categories: "Najobľúbenejšie kategórie",
    Most_Recent_Categories: "Najnovšie kategórie",
    Events_Label: "Udalosti",
    Forums_Label: "Fóra",
    Issues_Label: "Problémy",
    KnowledgeMgmt_Most_Popular_Articles: "Najobľúbenejšie články",
    KnowledgeMgmt_Most_Recent_Articles: "Najnovšie články",
    Knowledge_Base_Label: "Vedomostná databáza",
    Knowledge_Article_Unavailable: "Článok je nedostupný",
    Browse_The_KB: "Prehľadávať vedomostnú databázu",
    Popular_Topics: "Populárne témy",
    Related_Categories_DefaultText: "Súvisiace kategórie",
    Get_Help_DefaultText: "Získajte pomoc",
    Find_Your_Product: "Hľadať váš produkt",
    View_More: "Zobraziť viac",
    Most_Popular: "Najobľúbenejšie",
    Top_Rated_Articles: "Najlepšie hodnotené články",
    Case_Deflection_Suggested_Topics: "Navrhované témy",
    Sorting_Rating: "Priemerné hodnotenia používateľov",
    Sorting_Relevance: "Relevancia",
    Sorting_ViewCount: "Počet zobrazení",
    Sorting_Options: "Možnosti zoradenia",
    Facet_RecordType: "Typ záznamu",
    Facet_DateModified: "Dátum úpravy",
    Facet_Show_Less: "Zobraziť menej",
    Facet_Show_More: "Zobraziť viac",
    Facet_All: "Všetko",
    Facet_Rating: "Hodnotenie",
    Facet_Products: "Produkty",
    Pagination_Current_Page: "Aktuálna strana {0}",
    Pagination_First_Page: "Prvá strana",
    Pagination_Last_Page: "Posledná strana",
    Pagination_Next_Page: "Nasledujúca strana",
    Pagination_Page: "Strana {0}",
    Pagination_Previous_Page: "Predchádzajúca strana",
  }),
  "sl-SI": Object.freeze({
    Sign_In: "Vpis",
    Sign_Out: "Izpis",
    Profile: "Profil;",
    Search_DefaultText: "Iskanje",
    Discover_Contoso: "Odkrijte Contoso",
    Toggle_Navigation: "Preklop krmarjenja",
    Editable_Cancel_Label: "Prekliči",
    Submit_Button_Label_Text: "Pošlji",
    Poll_Results_Label: "Prikaži rezultate",
    Poll_Totals_Label: "Skupno število glasov:",
    Poll_Return_Label: "Nazaj na anketo",
    Poll_Archives_Heading: "Arhiv anket",
    Poll_DefaultText: "Anketa",
    All: "Vse",
    Search_Filter: "Filter za iskanje",
    Search_No_Results_Found: "Za to poizvedbo ni bilo najdenih nobenih rezultatov: ",
    Search_Results_Format_String: "Rezultati {0}–{1} od {2} za poizvedbo: ",
    Most_Popular_Categories: "Najbolj priljubljene kategorije",
    Most_Recent_Categories: "Najnovejše kategorije",
    Events_Label: "Dogodki",
    Forums_Label: "Forumi",
    Issues_Label: "Težave",
    KnowledgeMgmt_Most_Popular_Articles: "Najbolj priljubljeni članki",
    KnowledgeMgmt_Most_Recent_Articles: "Najnovejši članki",
    Knowledge_Base_Label: "Zbirka znanja",
    Knowledge_Article_Unavailable: "Članek ni na voljo",
    Browse_The_KB: "Prebrskaj zbirko znanja",
    Popular_Topics: "Priljubljene teme",
    Related_Categories_DefaultText: "Povezane kategorije",
    Get_Help_DefaultText: "Pridobi pomoč",
    Find_Your_Product: "Iskanje izdelka",
    View_More: "Prikaži več",
    Most_Popular: "Najbolj priljubljeno",
    Top_Rated_Articles: "Najbolje ocenjeni članki",
    Case_Deflection_Suggested_Topics: "Predlagane teme",
    Sorting_Rating: "Povprečne ocene uporabnikov",
    Sorting_Relevance: "Ustreznost",
    Sorting_ViewCount: "Število ogledov",
    Sorting_Options: "Možnosti razvrščanja",
    Facet_RecordType: "Vrsta zapisa",
    Facet_DateModified: "Datum spremembe",
    Facet_Show_Less: "Pokaži manj",
    Facet_Show_More: "Pokaži več",
    Facet_All: "Vse",
    Facet_Rating: "Ocena",
    Facet_Products: "Izdelki",
    Pagination_Current_Page: "Trenutna stran {0}",
    Pagination_First_Page: "Prva stran",
    Pagination_Last_Page: "Zadnja stran",
    Pagination_Next_Page: "Naslednja stran",
    Pagination_Page: "Stran {0}",
    Pagination_Previous_Page: "Prejšnja stran",
  }),
  "sr-Cyrl-CS": Object.freeze({
    Sign_In: "Пријави се",
    Sign_Out: "Одјави се",
    Profile: "Профил;",
    Search_DefaultText: "Претражи",
    Discover_Contoso: "Откријте Contoso",
    Toggle_Navigation: "Укључи/искључи навигацију",
    Editable_Cancel_Label: "Откажи",
    Submit_Button_Label_Text: "Проследи",
    Poll_Results_Label: "Прикажи резултате",
    Poll_Totals_Label: "Укупан број гласова:",
    Poll_Return_Label: "Врати се на анкету",
    Poll_Archives_Heading: "Архиве анкета",
    Poll_DefaultText: "Анкета",
    All: "Све",
    Search_Filter: "Филтер претраге",
    Search_No_Results_Found: "Нису пронађени резултати за овај упит: ",
    Search_Results_Format_String: "Резултати {0} – {1} од {2} за упит: ",
    Most_Popular_Categories: "Најпопуларније категорије",
    Most_Recent_Categories: "Најновије категорије",
    Events_Label: "Догађаји",
    Forums_Label: "Форуми",
    Issues_Label: "Проблеми",
    KnowledgeMgmt_Most_Popular_Articles: "Најпопуларнији чланци",
    KnowledgeMgmt_Most_Recent_Articles: "Најновији чланци",
    Knowledge_Base_Label: "База знања",
    Knowledge_Article_Unavailable: "Чланак је недоступан",
    Browse_The_KB: "Претражи базу знања",
    Popular_Topics: "Популарне теме",
    Related_Categories_DefaultText: "Сродне категорије",
    Get_Help_DefaultText: "Пронађите помоћ",
    Find_Your_Product: "Пронађите производ",
    View_More: "Прикажи више",
    Most_Popular: "Најпопуларније",
    Top_Rated_Articles: "Најбоље оцењени чланци",
    Case_Deflection_Suggested_Topics: "Предложене теме",
    Sorting_Rating: "Просечне оцене корисника",
    Sorting_Relevance: "Релевантност",
    Sorting_ViewCount: "Број приказа",
    Sorting_Options: "Опције сортирања",
    Facet_RecordType: "Врста записа",
    Facet_DateModified: "Датум измене",
    Facet_Show_Less: "Прикажи мање",
    Facet_Show_More: "Покажи више",
    Facet_All: "Све",
    Facet_Rating: "Оцена",
    Facet_Products: "Производи",
    Pagination_Current_Page: "Тренутна страница {0}",
    Pagination_First_Page: "Прва страница",
    Pagination_Last_Page: "Последња страница",
    Pagination_Next_Page: "Следећа страница",
    Pagination_Page: "Страница {0}",
    Pagination_Previous_Page: "Претходна страница",
  }),
  "sr-Cyrl-RS": Object.freeze({
    Sign_In: "Пријави се",
    Sign_Out: "Одјави се",
    Profile: "Профил;",
    Search_DefaultText: "Претражи",
    Discover_Contoso: "Откријте Contoso",
    Toggle_Navigation: "Укључи/искључи навигацију",
    Editable_Cancel_Label: "Откажи",
    Submit_Button_Label_Text: "Проследи",
    Poll_Results_Label: "Прикажи резултате",
    Poll_Totals_Label: "Укупан број гласова:",
    Poll_Return_Label: "Врати се на анкету",
    Poll_Archives_Heading: "Архиве анкета",
    Poll_DefaultText: "Анкета",
    All: "Све",
    Search_Filter: "Филтер претраге",
    Search_No_Results_Found: "Нису пронађени резултати за овај упит: ",
    Search_Results_Format_String: "Резултати {0} – {1} од {2} за упит: ",
    Most_Popular_Categories: "Најпопуларније категорије",
    Most_Recent_Categories: "Најновије категорије",
    Events_Label: "Догађаји",
    Forums_Label: "Форуми",
    Issues_Label: "Проблеми",
    KnowledgeMgmt_Most_Popular_Articles: "Најпопуларнији чланци",
    KnowledgeMgmt_Most_Recent_Articles: "Најновији чланци",
    Knowledge_Base_Label: "База знања",
    Knowledge_Article_Unavailable: "Чланак је недоступан",
    Browse_The_KB: "Претражи базу знања",
    Popular_Topics: "Популарне теме",
    Related_Categories_DefaultText: "Сродне категорије",
    Get_Help_DefaultText: "Пронађите помоћ",
    Find_Your_Product: "Пронађите производ",
    View_More: "Прикажи више",
    Most_Popular: "Најпопуларније",
    Top_Rated_Articles: "Најбоље оцењени чланци",
    Case_Deflection_Suggested_Topics: "Предложене теме",
    Sorting_Rating: "Просечне оцене корисника",
    Sorting_Relevance: "Релевантност",
    Sorting_ViewCount: "Број приказа",
    Sorting_Options: "Опције сортирања",
    Facet_RecordType: "Врста записа",
    Facet_DateModified: "Датум измене",
    Facet_Show_Less: "Прикажи мање",
    Facet_Show_More: "Покажи више",
    Facet_All: "Све",
    Facet_Rating: "Оцена",
    Facet_Products: "Производи",
    Pagination_Current_Page: "Тренутна страница {0}",
    Pagination_First_Page: "Прва страница",
    Pagination_Last_Page: "Последња страница",
    Pagination_Next_Page: "Следећа страница",
    Pagination_Page: "Страница {0}",
    Pagination_Previous_Page: "Претходна страница",
  }),
  "sr-Latn-CS": Object.freeze({
    Sign_In: "Prijavi se",
    Sign_Out: "Odjavi se",
    Profile: "Profil;",
    Search_DefaultText: "Pretraži",
    Discover_Contoso: "Otkrijte Contoso",
    Toggle_Navigation: "Uključi/isključi navigaciju",
    Editable_Cancel_Label: "Otkaži",
    Submit_Button_Label_Text: "Prosledi",
    Poll_Results_Label: "Prikaži rezultate",
    Poll_Totals_Label: "Ukupan broj glasova:",
    Poll_Return_Label: "Vrati se na anketu",
    Poll_Archives_Heading: "Arhive anketa",
    Poll_DefaultText: "Anketa",
    All: "Sve",
    Search_Filter: "Filter pretrage",
    Search_No_Results_Found: "Nisu pronađeni rezultati za ovaj upit: ",
    Search_Results_Format_String: "Rezultati {0} – {1} od {2} za upit: ",
    Most_Popular_Categories: "Najpopularnije kategorije",
    Most_Recent_Categories: "Najnovije kategorije",
    Events_Label: "Događaji",
    Forums_Label: "Forumi",
    Issues_Label: "Problemi",
    KnowledgeMgmt_Most_Popular_Articles: "Najpopularniji članci",
    KnowledgeMgmt_Most_Recent_Articles: "Najnoviji članci",
    Knowledge_Base_Label: "Baza znanja",
    Knowledge_Article_Unavailable: "Članak je nedostupan",
    Browse_The_KB: "Pretraži bazu znanja",
    Popular_Topics: "Popularne teme",
    Related_Categories_DefaultText: "Srodne kategorije",
    Get_Help_DefaultText: "Pronađite pomoć",
    Find_Your_Product: "Pronađite proizvod",
    View_More: "Prikaži više",
    Most_Popular: "Najpopularnije",
    Top_Rated_Articles: "Najbolje ocenjeni članci",
    Case_Deflection_Suggested_Topics: "Predložene teme",
    Sorting_Rating: "Prosečne ocene korisnika",
    Sorting_Relevance: "Relevantnost",
    Sorting_ViewCount: "Broj prikaza",
    Sorting_Options: "Opcije sortiranja",
    Facet_RecordType: "Vrsta zapisa",
    Facet_DateModified: "Datum izmene",
    Facet_Show_Less: "Prikaži manje",
    Facet_Show_More: "Pokaži više",
    Facet_All: "Sve",
    Facet_Rating: "Ocena",
    Facet_Products: "Proizvodi",
    Pagination_Current_Page: "Trenutna stranica {0}",
    Pagination_First_Page: "Prva stranica",
    Pagination_Last_Page: "Poslednja stranica",
    Pagination_Next_Page: "Sledeća stranica",
    Pagination_Page: "Stranica {0}",
    Pagination_Previous_Page: "Prethodna stranica",
  }),
  "sr-Latn-RS": Object.freeze({
    Sign_In: "Prijavi se",
    Sign_Out: "Odjavi se",
    Profile: "Profil;",
    Search_DefaultText: "Pretraži",
    Discover_Contoso: "Otkrijte Contoso",
    Toggle_Navigation: "Uključi/isključi navigaciju",
    Editable_Cancel_Label: "Otkaži",
    Submit_Button_Label_Text: "Prosledi",
    Poll_Results_Label: "Prikaži rezultate",
    Poll_Totals_Label: "Ukupan broj glasova:",
    Poll_Return_Label: "Vrati se na anketu",
    Poll_Archives_Heading: "Arhive anketa",
    Poll_DefaultText: "Anketa",
    All: "Sve",
    Search_Filter: "Filter pretrage",
    Search_No_Results_Found: "Nisu pronađeni rezultati za ovaj upit: ",
    Search_Results_Format_String: "Rezultati {0} – {1} od {2} za upit: ",
    Most_Popular_Categories: "Najpopularnije kategorije",
    Most_Recent_Categories: "Najnovije kategorije",
    Events_Label: "Događaji",
    Forums_Label: "Forumi",
    Issues_Label: "Problemi",
    KnowledgeMgmt_Most_Popular_Articles: "Najpopularniji članci",
    KnowledgeMgmt_Most_Recent_Articles: "Najnoviji članci",
    Knowledge_Base_Label: "Baza znanja",
    Knowledge_Article_Unavailable: "Članak je nedostupan",
    Browse_The_KB: "Pretraži bazu znanja",
    Popular_Topics: "Popularne teme",
    Related_Categories_DefaultText: "Srodne kategorije",
    Get_Help_DefaultText: "Pronađite pomoć",
    Find_Your_Product: "Pronađite proizvod",
    View_More: "Prikaži više",
    Most_Popular: "Najpopularnije",
    Top_Rated_Articles: "Najbolje ocenjeni članci",
    Case_Deflection_Suggested_Topics: "Predložene teme",
    Sorting_Rating: "Prosečne ocene korisnika",
    Sorting_Relevance: "Relevantnost",
    Sorting_ViewCount: "Broj prikaza",
    Sorting_Options: "Opcije sortiranja",
    Facet_RecordType: "Vrsta zapisa",
    Facet_DateModified: "Datum izmene",
    Facet_Show_Less: "Prikaži manje",
    Facet_Show_More: "Pokaži više",
    Facet_All: "Sve",
    Facet_Rating: "Ocena",
    Facet_Products: "Proizvodi",
    Pagination_Current_Page: "Trenutna stranica {0}",
    Pagination_First_Page: "Prva stranica",
    Pagination_Last_Page: "Poslednja stranica",
    Pagination_Next_Page: "Sledeća stranica",
    Pagination_Page: "Stranica {0}",
    Pagination_Previous_Page: "Prethodna stranica",
  }),
  "sv-SE": Object.freeze({
    Sign_In: "Logga in",
    Sign_Out: "Logga ut",
    Profile: "Profil;",
    Search_DefaultText: "Sök",
    Discover_Contoso: "Upptäck Contoso",
    Toggle_Navigation: "Växla navigering",
    Editable_Cancel_Label: "Avbryt",
    Submit_Button_Label_Text: "Skicka",
    Poll_Results_Label: "Visa resultat",
    Poll_Totals_Label: "Totala röster:",
    Poll_Return_Label: "Återgå till undersökning",
    Poll_Archives_Heading: "Avsökningsarkiv",
    Poll_DefaultText: "Undersökning",
    All: "Alla",
    Search_Filter: "Sökfilter",
    Search_No_Results_Found: "Inga bästa träffar hittades för denna fråga: ",
    Search_Results_Format_String: "Resultaten {0}–{1} av {2} för frågan: ",
    Most_Popular_Categories: "Mest populära kategorierna",
    Most_Recent_Categories: "Senaste kategorierna",
    Events_Label: "Händelser",
    Forums_Label: "Forum",
    Issues_Label: "Problem",
    KnowledgeMgmt_Most_Popular_Articles: "Mest populära artiklarna",
    KnowledgeMgmt_Most_Recent_Articles: "Senaste artiklarna",
    Knowledge_Base_Label: "Kunskapsbasen",
    Knowledge_Article_Unavailable: "Artikeln är inte tillgänglig",
    Browse_The_KB: "Bläddra i KB",
    Popular_Topics: "Populära ämnen",
    Related_Categories_DefaultText: "Relaterade kategorier",
    Get_Help_DefaultText: "Få hjälp",
    Find_Your_Product: "Hitta din produkt",
    View_More: "Visa mer",
    Most_Popular: "Populärast",
    Top_Rated_Articles: "Topprankade artiklar",
    Case_Deflection_Suggested_Topics: "Förslag på ämnen",
    Sorting_Rating: "Genomsnittligt användaromdöme",
    Sorting_Relevance: "Relevans",
    Sorting_ViewCount: "Antal visningar",
    Sorting_Options: "Sorteringsalternativ",
    Facet_RecordType: "Posttyp",
    Facet_DateModified: "Ändrat den",
    Facet_Show_Less: "Visa mindre",
    Facet_Show_More: "Visa mer",
    Facet_All: "Alla",
    Facet_Rating: "Klassificering",
    Facet_Products: "Produkter",
    Pagination_Current_Page: "Aktuell sida {0}",
    Pagination_First_Page: "Första sidan",
    Pagination_Last_Page: "Sista sidan",
    Pagination_Next_Page: "Nästa sida",
    Pagination_Page: "Sida {0}",
    Pagination_Previous_Page: "Föregående sida",
  }),
  "th-TH": Object.freeze({
    Sign_In: "ลงชื่อเข้าใช้",
    Sign_Out: "ลงชื่อออก",
    Profile: "โปรไฟล์;",
    Search_DefaultText: "ค้นหา",
    Discover_Contoso: "ค้นหา Contoso",
    Toggle_Navigation: "สลับเปิดปิดการนำทาง",
    Editable_Cancel_Label: "ยกเลิก",
    Submit_Button_Label_Text: "ส่ง",
    Poll_Results_Label: "ดูผลลัพธ์",
    Poll_Totals_Label: "จำนวนการลงคะแนนทั้งหมด:",
    Poll_Return_Label: "กลับไปยังการสำรวจ",
    Poll_Archives_Heading: "ข้อมูลเก็บถาวรของการสำรวจ",
    Poll_DefaultText: "การสำรวจ",
    All: "ทั้งหมด",
    Search_Filter: "ตัวกรองการค้นหา",
    Search_No_Results_Found: "ไม่พบผลลัพธ์สำหรับการสอบถามนี้: ",
    Search_Results_Format_String: "ผลลัพธ์ {0} - {1} จาก {2} สำหรับการสอบถาม: ",
    Most_Popular_Categories: "ประเภทที่ได้รับความนิยมสูงสุด",
    Most_Recent_Categories: "ประเภทล่าสุด",
    Events_Label: "เหตุการณ์",
    Forums_Label: "ฟอรั่ม",
    Issues_Label: "ปัญหา",
    KnowledgeMgmt_Most_Popular_Articles: "บทความที่ได้รับความนิยมสูงสุด",
    KnowledgeMgmt_Most_Recent_Articles: "บทความล่าสุด",
    Knowledge_Base_Label: "ฐานข้อมูลองค์ความรู้",
    Knowledge_Article_Unavailable: "บทความไม่พร้อมใช้งาน",
    Browse_The_KB: "เรียกดู KB",
    Popular_Topics: "หัวข้อยอดนิยม",
    Related_Categories_DefaultText: "ประเภทที่เกี่ยวข้อง",
    Get_Help_DefaultText: "รับความช่วยเหลือ",
    Find_Your_Product: "ค้นหาผลิตภัณฑ์ของคุณ",
    View_More: "ดูเพิ่มเติม",
    Most_Popular: "ได้รับความนิยมสูงสุด",
    Top_Rated_Articles: "บทความที่ได้รับการจัดอันดับสูงสุด",
    Case_Deflection_Suggested_Topics: "หัวข้อที่เสนอแนะ",
    Sorting_Rating: "การให้คะแนนผู้ใช้โดยเฉลี่ย",
    Sorting_Relevance: "ความเกี่ยวข้อง",
    Sorting_ViewCount: "จำนวนการดู",
    Sorting_Options: "ตัวเลือกการเรียง",
    Facet_RecordType: "ชนิดของเรกคอร์ด",
    Facet_DateModified: "วันที่ปรับเปลี่ยน",
    Facet_Show_Less: "แสดงน้อยลง",
    Facet_Show_More: "แสดงเพิ่มเติม",
    Facet_All: "ทั้งหมด",
    Facet_Rating: "การให้คะแนน",
    Facet_Products: "ผลิตภัณฑ์",
    Pagination_Current_Page: "หน้าปัจจุบัน {0}",
    Pagination_First_Page: "หน้าแรก",
    Pagination_Last_Page: "หน้าสุดท้าย",
    Pagination_Next_Page: "หน้าถัดไป",
    Pagination_Page: "หน้า {0}",
    Pagination_Previous_Page: "หน้าก่อนหน้า",
  }),
  "tr-TR": Object.freeze({
    Sign_In: "Oturum Aç",
    Sign_Out: "Oturumu Kapat",
    Profile: "Profil;",
    Search_DefaultText: "Arama",
    Discover_Contoso: "Contoso'yu Keşfet",
    Toggle_Navigation: "Gezintiyi değiştir",
    Editable_Cancel_Label: "İptal",
    Submit_Button_Label_Text: "Gönder",
    Poll_Results_Label: "Sonuçları Görüntüle",
    Poll_Totals_Label: "Toplam Oy Sayısı:",
    Poll_Return_Label: "Ankete Dön",
    Poll_Archives_Heading: "Anket Arşivleri",
    Poll_DefaultText: "Anket",
    All: "Tümü",
    Search_Filter: "Arama Filtresi",
    Search_No_Results_Found: "Bu sorgu için sonuç bulunamadı: ",
    Search_Results_Format_String: "Sorgu için {0} - {1} / {2} sonuç: ",
    Most_Popular_Categories: "En Popüler Kategoriler",
    Most_Recent_Categories: "En Yeni Kategoriler",
    Events_Label: "Olaylar",
    Forums_Label: "Forumlar",
    Issues_Label: "Sorunlar",
    KnowledgeMgmt_Most_Popular_Articles: "En Popüler Makaleler",
    KnowledgeMgmt_Most_Recent_Articles: "En Yeni Makaleler",
    Knowledge_Base_Label: "Bilgi Bankası",
    Knowledge_Article_Unavailable: "Makale Yok",
    Browse_The_KB: "BB'ye göz at",
    Popular_Topics: "Popüler Konular",
    Related_Categories_DefaultText: "İlgili Kategoriler",
    Get_Help_DefaultText: "Yardım Al",
    Find_Your_Product: "Ürününüzü Bulun",
    View_More: "Daha Fazlasını Göster",
    Most_Popular: "En Popüler",
    Top_Rated_Articles: "En Beğenilen Makaleler",
    Case_Deflection_Suggested_Topics: "Önerilen Konular",
    Sorting_Rating: "Ortalama Kullanıcı Derecelendirmeleri",
    Sorting_Relevance: "İlgi",
    Sorting_ViewCount: "Görüntüleme Sayısı",
    Sorting_Options: "Sıralama seçenekleri",
    Facet_RecordType: "Kayıt Türü",
    Facet_DateModified: "Değiştirilme tarihi",
    Facet_Show_Less: "Daha az göster",
    Facet_Show_More: "Daha fazla göster",
    Facet_All: "Tümü",
    Facet_Rating: "Derecelendirme",
    Facet_Products: "Ürünler",
    Pagination_Current_Page: "Geçerli sayfa {0}",
    Pagination_First_Page: "İlk sayfa",
    Pagination_Last_Page: "Son sayfa",
    Pagination_Next_Page: "Sonraki sayfa",
    Pagination_Page: "Sayfa {0}",
    Pagination_Previous_Page: "Önceki sayfa",
  }),
  "uk-UA": Object.freeze({
    Sign_In: "Вхід",
    Sign_Out: "Вихід",
    Profile: "Профіль;",
    Search_DefaultText: "Пошук",
    Discover_Contoso: "Знайомство з Contoso",
    Toggle_Navigation: "Активувати область переходів",
    Editable_Cancel_Label: "Скасувати",
    Submit_Button_Label_Text: "Надіслати",
    Poll_Results_Label: "Перегляд результатів",
    Poll_Totals_Label: "Усього голосів:",
    Poll_Return_Label: "Повернутися до опитування",
    Poll_Archives_Heading: "Архіви опитувань",
    Poll_DefaultText: "Опитування",
    All: "Усі",
    Search_Filter: "Фільтр пошуку",
    Search_No_Results_Found: "Результати за цим запитом не знайдені: ",
    Search_Results_Format_String: "Результати {0}–{1} з {2} за запитом: ",
    Most_Popular_Categories: "Найпопулярніші категорії",
    Most_Recent_Categories: "Останні категорії",
    Events_Label: "Події",
    Forums_Label: "Форуми",
    Issues_Label: "Запитання",
    KnowledgeMgmt_Most_Popular_Articles: "Найпопулярніші статті",
    KnowledgeMgmt_Most_Recent_Articles: "Останні статті",
    Knowledge_Base_Label: "База знань",
    Knowledge_Article_Unavailable: "Стаття недоступна",
    Browse_The_KB: "Огляд бази знань",
    Popular_Topics: "Популярні розділи",
    Related_Categories_DefaultText: "Пов’язані категорії",
    Get_Help_DefaultText: "Отримання довідки",
    Find_Your_Product: "Пошук продукту",
    View_More: "Більше",
    Most_Popular: "Найпопулярніші",
    Top_Rated_Articles: "Найбільш рейтингові статті",
    Case_Deflection_Suggested_Topics: "Пропоновані теми",
    Sorting_Rating: "Середня оцінка користувачів",
    Sorting_Relevance: "Відповідність",
    Sorting_ViewCount: "Кількість переглядів",
    Sorting_Options: "Параметри сортування",
    Facet_RecordType: "Тип запису",
    Facet_DateModified: "Дата змінення",
    Facet_Show_Less: "Згорнути",
    Facet_Show_More: "Розгорнути",
    Facet_All: "Усі",
    Facet_Rating: "Оцінка",
    Facet_Products: "Продукти",
    Pagination_Current_Page: "Поточна сторінка {0}",
    Pagination_First_Page: "Перша сторінка",
    Pagination_Last_Page: "Остання сторінка",
    Pagination_Next_Page: "Наступна сторінка",
    Pagination_Page: "Стор. {0}",
    Pagination_Previous_Page: "Попередня сторінка",
  }),
  "vi-VN": Object.freeze({
    Sign_In: "Đăng nhập",
    Sign_Out: "Đăng xuất",
    Profile: "Cấu hình;",
    Search_DefaultText: "Tìm kiếm",
    Discover_Contoso: "Khám phá Contoso",
    Toggle_Navigation: "Chuyển đổi điều hướng",
    Editable_Cancel_Label: "Hủy",
    Submit_Button_Label_Text: "Gửi",
    Poll_Results_Label: "Xem Kết quả",
    Poll_Totals_Label: "Tổng số Biểu quyết:",
    Poll_Return_Label: "Quay lại Cuộc thăm dò",
    Poll_Archives_Heading: "Lưu trữ Cuộc thăm dò",
    Poll_DefaultText: "Cuộc thăm dò",
    All: "Tất cả",
    Search_Filter: "Bộ lọc Tìm kiếm",
    Search_No_Results_Found: "Không tìm thấy kết quả cho truy vấn này: ",
    Search_Results_Format_String: "Kết quả {0} - {1} của {2} cho truy vấn: ",
    Most_Popular_Categories: "Thể loại Phổ biến Nhất",
    Most_Recent_Categories: "Thể loại Gần đây Nhất",
    Events_Label: "Sự kiện",
    Forums_Label: "Diễn đàn",
    Issues_Label: "Vấn đề",
    KnowledgeMgmt_Most_Popular_Articles: "Bài viết Phổ biến Nhất",
    KnowledgeMgmt_Most_Recent_Articles: "Bài viết Gần đây Nhất",
    Knowledge_Base_Label: "Cơ sở kiến thức",
    Knowledge_Article_Unavailable: "Bài viết Không có sẵn",
    Browse_The_KB: "Duyệt xem KB",
    Popular_Topics: "Chủ đề Phổ biến",
    Related_Categories_DefaultText: "Thể loại liên quan",
    Get_Help_DefaultText: "Nhận trợ giúp",
    Find_Your_Product: "Tìm Sản phẩm của bạn",
    View_More: "Xem thêm",
    Most_Popular: "Phổ biến Nhất",
    Top_Rated_Articles: "Bài viết Được xếp hạng Hàng đầu",
    Case_Deflection_Suggested_Topics: "Chủ đề Gợi ý",
    Sorting_Rating: "Xếp hạng Người dùng Trung bình",
    Sorting_Relevance: "Mức độ liên quan",
    Sorting_ViewCount: "Số lần Xem",
    Sorting_Options: "Tùy chọn sắp xếp",
    Facet_RecordType: "Loại Bản ghi",
    Facet_DateModified: "Ngày sửa",
    Facet_Show_Less: "Ẩn bớt",
    Facet_Show_More: "Hiện thêm",
    Facet_All: "Tất cả",
    Facet_Rating: "Xếp hạng",
    Facet_Products: "Các sản phẩm",
    Pagination_Current_Page: "Trang hiện tại {0}",
    Pagination_First_Page: "Trang đầu",
    Pagination_Last_Page: "Trang cuối",
    Pagination_Next_Page: "Trang sau",
    Pagination_Page: "Trang {0}",
    Pagination_Previous_Page: "Trang trước",
  }),
  "zh-CN": Object.freeze({
    Sign_In: "登录",
    Sign_Out: "注销",
    Profile: "个人资料；",
    Search_DefaultText: "搜索",
    Discover_Contoso: "了解 Contoso",
    Toggle_Navigation: "切换导航",
    Editable_Cancel_Label: "取消",
    Submit_Button_Label_Text: "提交",
    Poll_Results_Label: "查看结果",
    Poll_Totals_Label: "总票数:",
    Poll_Return_Label: "返回到民意调查",
    Poll_Archives_Heading: "投票存档",
    Poll_DefaultText: "投票",
    All: "所有",
    Search_Filter: "搜索筛选器",
    Search_No_Results_Found: "未找到此查询的结果: ",
    Search_Results_Format_String: "以下查询的结果 {0} - {1}/{2}: ",
    Most_Popular_Categories: "最受欢迎的类别",
    Most_Recent_Categories: "最新的类别",
    Events_Label: "事件",
    Forums_Label: "论坛",
    Issues_Label: "问题",
    KnowledgeMgmt_Most_Popular_Articles: "最受欢迎的文章",
    KnowledgeMgmt_Most_Recent_Articles: "最新文章",
    Knowledge_Base_Label: "知识库",
    Knowledge_Article_Unavailable: "文章不可用",
    Browse_The_KB: "浏览知识库",
    Popular_Topics: "热门主题",
    Related_Categories_DefaultText: "相关类别",
    Get_Help_DefaultText: "获取帮助",
    Find_Your_Product: "查找您的产品",
    View_More: "查看更多",
    Most_Popular: "最受欢迎的",
    Top_Rated_Articles: "评级最高的文章",
    Case_Deflection_Suggested_Topics: "建议的主题",
    Sorting_Rating: "平均用户评分",
    Sorting_Relevance: "相关性",
    Sorting_ViewCount: "视图数量",
    Sorting_Options: "排序选项",
    Facet_RecordType: "记录类型",
    Facet_DateModified: "修改日期",
    Facet_Show_Less: "显示更少",
    Facet_Show_More: "显示更多",
    Facet_All: "所有",
    Facet_Rating: "评级",
    Facet_Products: "产品",
    Pagination_Current_Page: "当前页 {0}",
    Pagination_First_Page: "第一页",
    Pagination_Last_Page: "最后一页",
    Pagination_Next_Page: "下一页",
    Pagination_Page: "第 {0} 页",
    Pagination_Previous_Page: "上一页",
  }),
  "zh-HK": Object.freeze({
    Sign_In: "登入",
    Sign_Out: "登出",
    Profile: "設定檔:",
    Search_DefaultText: "搜尋",
    Discover_Contoso: "探索 Contoso",
    Toggle_Navigation: "切換導覽模式",
    Editable_Cancel_Label: "取消",
    Submit_Button_Label_Text: "送出",
    Poll_Results_Label: "檢視結果",
    Poll_Totals_Label: "總票數:",
    Poll_Return_Label: "返回投票",
    Poll_Archives_Heading: "投票封存",
    Poll_DefaultText: "投票",
    All: "全部",
    Search_Filter: "搜尋篩選",
    Search_No_Results_Found: "找不到此查詢的結果:",
    Search_Results_Format_String: "查詢結果 {0} - {1} / {2}:",
    Most_Popular_Categories: "最熱門類別",
    Most_Recent_Categories: "最近的類別",
    Events_Label: "事件",
    Forums_Label: "論壇",
    Issues_Label: "問題",
    KnowledgeMgmt_Most_Popular_Articles: "最熱門文章",
    KnowledgeMgmt_Most_Recent_Articles: "最近的文章",
    Knowledge_Base_Label: "知識庫",
    Knowledge_Article_Unavailable: "文章無法使用",
    Browse_The_KB: "瀏覽知識庫",
    Popular_Topics: "熱門主題",
    Related_Categories_DefaultText: "相關類別",
    Get_Help_DefaultText: "取得說明",
    Find_Your_Product: "尋找您的產品",
    View_More: "檢視更多",
    Most_Popular: "最常用",
    Top_Rated_Articles: "最高分文章",
    Case_Deflection_Suggested_Topics: "建議的主題",
    Sorting_Rating: "平均使用者評分",
    Sorting_Relevance: "相關性",
    Sorting_ViewCount: "檢視計數",
    Sorting_Options: "排序選項",
    Facet_RecordType: "記錄類型",
    Facet_DateModified: "修改日期",
    Facet_Show_Less: "顯示較少內容",
    Facet_Show_More: "顯示更多內容",
    Facet_All: "全部",
    Facet_Rating: "評分",
    Facet_Products: "產品",
    Pagination_Current_Page: "目前頁面 {0}",
    Pagination_First_Page: "第一頁",
    Pagination_Last_Page: "最後一頁",
    Pagination_Next_Page: "下一頁",
    Pagination_Page: "頁面 {0}",
    Pagination_Previous_Page: "上一頁",
  }),
  "zh-TW": Object.freeze({
    Sign_In: "登入",
    Sign_Out: "登出",
    Profile: "設定檔:",
    Search_DefaultText: "搜尋",
    Discover_Contoso: "探索 Contoso",
    Toggle_Navigation: "切換導覽模式",
    Editable_Cancel_Label: "取消",
    Submit_Button_Label_Text: "送出",
    Poll_Results_Label: "檢視結果",
    Poll_Totals_Label: "總票數:",
    Poll_Return_Label: "返回投票",
    Poll_Archives_Heading: "投票封存",
    Poll_DefaultText: "投票",
    All: "全部",
    Search_Filter: "搜尋篩選",
    Search_No_Results_Found: "找不到此查詢的結果:",
    Search_Results_Format_String: "查詢結果 {0} - {1} / {2}:",
    Most_Popular_Categories: "最熱門類別",
    Most_Recent_Categories: "最近的類別",
    Events_Label: "事件",
    Forums_Label: "論壇",
    Issues_Label: "問題",
    KnowledgeMgmt_Most_Popular_Articles: "最熱門文章",
    KnowledgeMgmt_Most_Recent_Articles: "最近的文章",
    Knowledge_Base_Label: "知識庫",
    Knowledge_Article_Unavailable: "文章無法使用",
    Browse_The_KB: "瀏覽知識庫",
    Popular_Topics: "熱門主題",
    Related_Categories_DefaultText: "相關類別",
    Get_Help_DefaultText: "取得說明",
    Find_Your_Product: "尋找您的產品",
    View_More: "檢視更多",
    Most_Popular: "最常用",
    Top_Rated_Articles: "最高分文章",
    Case_Deflection_Suggested_Topics: "建議的主題",
    Sorting_Rating: "平均使用者評分",
    Sorting_Relevance: "相關性",
    Sorting_ViewCount: "檢視計數",
    Sorting_Options: "排序選項",
    Facet_RecordType: "記錄類型",
    Facet_DateModified: "修改日期",
    Facet_Show_Less: "顯示較少內容",
    Facet_Show_More: "顯示更多內容",
    Facet_All: "全部",
    Facet_Rating: "評分",
    Facet_Products: "產品",
    Pagination_Current_Page: "目前頁面 {0}",
    Pagination_First_Page: "第一頁",
    Pagination_Last_Page: "最後一頁",
    Pagination_Next_Page: "下一頁",
    Pagination_Page: "頁面 {0}",
    Pagination_Previous_Page: "上一頁",
  }),
});
