import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
import { browserLaunchOptions } from '../lib/browser-launch.mjs';
import { operationFixture } from '../test/operation-fixture.mjs';

test('Operations admin discovers exports, saves a local response and restores its placeholder', async t => {
  const {app}=await operationFixture(t);
  const browser=await chromium.launch(browserLaunchOptions({headless:true}));
  t.after(()=>browser.close());
  const page=await browser.newPage({viewport:{width:1280,height:900}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(app.url+'/__sim/#operations');
  const form=page.locator('[data-operation-key="server-logic:sample"]');
  await form.waitFor();
  assert.equal(await form.locator('[name=mode]').inputValue(),'placeholder');
  assert.equal(await page.locator('h2').filter({hasText:'Connector workflow'}).count(),1);
  await form.locator('[name=mode]').selectOption('mock');
  await form.locator('[name=body]').fill('{"reviewed":"browser"}');
  await form.getByRole('button',{name:'Save local behavior'}).click();
  await page.getByRole('button',{name:'Use source default'}).waitFor();
  const result=await (await fetch(app.url+'/_api/serverlogics/sample')).json();
  assert.deepEqual(JSON.parse(result.data),{reviewed:'browser'});
  await page.getByRole('button',{name:'Use source default'}).click();
  await page.waitForFunction(()=>document.querySelector('[data-operation-key="server-logic:sample"] [name=mode]')?.value==='placeholder');
  assert.equal((await fetch(app.url+'/_api/serverlogics/sample')).status,501);
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
  assert.deepEqual(errors,[]);
});
